stenciljs/site

- docs-md/advanced/ssr/index.md
The server compiler looks for `<namespace>.registery.json` under the build path. This means that the build path needs to be `www/build`, and the namespace needs to be `app` since that's the stencil default.
> docs(): fix SSR example

- docs-md/basics/using-events.md
I tested the sample and noticed that the event.`data` doesn't exists! 
I found that to correctly access to the payload emitted in the CustomEvent you need to read `event.detail`
> Fix docs @Listen sample to use event.detail

- docs-md/basics/my-first-component.md
The sample show and use a property firstName, but in the below description you refer it as simple "name" so I fix the code to match it
> Fix docs: align sample code with description

- src/components/demos-page/demos-page.tsx
- src/components/landing-page/landing-page.tsx
- src/components/site-header/site-header.tsx
- src/components/youtube-video/youtube-video.tsx
This changes improve:
- Accessibility up to 100 thanks to add `title` on links and iframes.
- Best practices thanks to use `rel="noopener"` on anchor links to improve performance and security vulnerabilities
> Fix(): Perf lighthouse score

- docs-md/basics/templating.md
As reported in https://github.com/ionic-team/stencil/issues/143 the map statement is laking the braces to mark them as an expression statement in jsx.
> Fix inline js not marked as expression in jsx

- docs-md/advanced/ssr/index.md
The Node.js example at https://stenciljs.com/docs/server-side-rendering implements a callback that accepts an `err` and `html` argument, but looking at the actual invocation of the callback in the `@stencil/core` codebase, it appears that the callback should always accept one argument, representing a HydateResults object.
We should update the example to be functional, and handle errors properly by checking if diagnostics is not empty before returning rendered HTML.
Sources:
Callback invocation in case of error: https://github.com/ionic-team/stencil/blob/d1e129eb718333ae631253c81c1ba5ca1921e2d2/src/server/renderer.ts#L62
Callback invocation in case of success: https://github.com/ionic-team/stencil/blob/d1e129eb718333ae631253c81c1ba5ca1921e2d2/src/server/hydrate-html.ts#L23
HydateResults …
> Server side rendering example not functional

- docs-md/basics/templating.md
This PR fixes the templating loops example, as the original doesn't return the inner body of the map function.
> Fixes loops example

- docs-md/basics/stencil-config.md
Just add more info to the stencil config example:
- Added service worker custom config.
- Added copy config.
> docs(): Add more info to stencil-config example

- src/components/resources-page/resources-page.tsx
I saw that the revealjs link on the resources page was not workng, trying to get this:
>https://stenciljs.com/lab.hakim.se/reveal-js/
I thought to make it point to the presentation link, but it is http:
>http://lab.hakim.se/reveal-js/#/
So i think its better to point it to the github repo using http:
>https://github.com/hakimel/reveal.js
> Fix(): Revealjs link not working

- docs-md/basics/stencil-config.md
Expand the documentation regarding the copy part of the configuration section on the website. Refers to #73
> docs(copy): add better description to copy config

- docs-md/basics/decorators.md
This updates the code examples in "Managing Component State" to use spread instead of `concat()`. In my opinion, spread makes it clearer that you're assembling a new array. Plus, you don't have to rely on the knowledge that `concat()` doesn't mutate. Definitely open to counter-points.
> docs() update state management examples for clarity

- docs-md/addons/stencil-router.md
The template literal usage in the documentation is not surrounded by `{}` when used in the JSX which yields a compilation error.
> docs(router): correct usage of template literals

- docs-md/advanced/distribution/index.md
> docs(advanced): correct script tag syntax error

- docs-md/addons/stencil-router.md
- docs-md/advanced/service-worker/index.md
- docs-md/basics/forms.md
- docs-md/basics/my-first-component.md
This is the fix for issue #98.
Other than the expected changes, my editor (VS Code) has automatically stripped a few blanks at the end of lines, which should have no effect.
> docs(several pages): fix typos and spelling errors

- docs-md/advanced/framework-integration/index.md
Fixed a typo I found while reading the docs.
> docs(): fix typo

- docs-md/advanced/distribution/index.md
👋 
I've been creating a distribution and it seems like those docs are outdated. Specifically, the keys that are required in `package.json` for a distribution look outdated:
```json
{
"main": "dist/collection/index.js",
"types": "dist/collection/index.d.ts",
"collection": "dist/collection/collection-manifest.json",
"files": [
"dist/"
],
"browser": "dist/myname.js"
}
```
The compiler actually threw a helpful error letting me know what needed updating. Here's what I think we want:
```json
"main": "dist/myname.js",
"types": "dist/types/components.d.ts",
"collection": "dist/collection/collection-manifest.json",
"files": [
"dist/"
]
```
Also, I don't believe we need the `browser` key anymore if it's the same as `main`.
> docs(distribution) update required package keys

- docs-md/advanced/distribution/index.md
Right now the paths are wrong (outdated?) and this wouldn't build.
> docs(distribution): fix paths in package.json

- src/docs-md/basics/decorators.md
Added documentation about **mutable** option in `@Prop` decorator as requested in https://github.com/ionic-team/stencil-site/issues/126.
Review over English grammar is very welcome.
> docs(prop): Add Prop mutable docs

- src/docs-content/basics/decorators.html
- src/docs-md/basics/decorators.md
Small typo "blow" changed to "below". Added a definite article for clarity/structure.
Modified pronoun so that it agreed with its antecedent in number. Components (plural) specify which props _they_ expect to receive. One component would specify which props _it_ expects to receive.
> docs(decorators): typo and pluralization

- src/docs-content/introduction/getting-started.html
Link to __router docs__ points to `/docs/routing` instead of `/docs/router` which results in effects like shown in #35
> Fix wrong link to router docs

- scripts/host-to-firebase.js
Without this line, the firebase.json file would keep getting larger (with duplicate data) every time the script is ran.
> Setting headers to empty array before pushing host data.

- src/components/site-menu/site-menu.tsx
- src/components/stencil-site/stencil-site.tsx
- src/docs-content/reference/host-element.html
- src/docs-md/reference/host-element.md
This adds a dedicated page to the Stencil docs for handling the host element. There's not a ton there, but I think it's an important page for people coming from something like React, where there isn't really a notion of host elements.
Totally open to style changes and content suggestions.
> docs(host-element): add host element docs page

- src/docs-md/reference/component-lifecycle.md
The following changes have been applied to the component lifecycle
section:
* Fix typo in `curent`.
* Example explanation is changed from timer to clock. The original
explanation stated that a timer was started as soon as the component was
loaded. This was not exact, as the information shown was the current
local time.
* `clearInterval` is called on `window` for consistency with
`window.setInterval`.
> [FIX] Some fixes for component lifecycle

- src/docs-content/framework-integration/ember.html
- src/docs-content/guides/framework-integration.html
- src/docs-md/framework-integration/ember.md
- src/docs-md/guides/framework-integration.md
I recently build [`ember-cli-stencil`](https://github.com/alexlafroscia/ember-cli-stencil) which makes it really, really easy to use Stencil components in an Ember app. With the addon installed, and at least one Stencil collection in your dependencies, it will handle all the additional work around discovering where the files are, importing them correctly and copying the lazy-loaded files into the right location in the `dist`. It also supports some "glue code" for better compatibility with older Ember versions ([see wiki for details](https://github.com/alexlafroscia/ember-cli-stencil/wiki/Ember-component-wrappers)).
I decided to just show the absolute minimal guide in the guide here and to instead redirect people to the addon README for additional details. If there's more information you …
> Add Ember to framework integration guide

- src/docs-content/guides/distribution.html
import my-component isn't a proper statement. It emphasizes that we are importing any component instead of published project/lib.
> docs(distribution): correction in import statement for importing published component

- src/docs-md/reference/component-lifecycle.md
`componentDidUpdate` docs erroneously refer to `componentWillUpdate` (copy-paste error).
>  Fix typo in `componentDidUpdate` docs

- src/docs-content/introduction/getting-started.html
npm init stencil components throws an error, the correct command is singular 'component'
This fixes #205
>  (#205) Fixed typo on getting started page. Components -> Component

- src/docs/components/events.md
Adds description of the options object accepted by the Event decorator, and specifies that usage in jsx applies to stencil compiled code
fix #218
> docs: improve event documentation

- src/components/app-marked/app-marked.tsx
which caused problems with overflows on mobile devices on pages with code blocks.
> Added missing app-marked stylesheet

- src/docs/testing/e2e-testing.md
```js
expect(null).toBeDefined()
```
would actually pass... `page.find()` returns `null` if it can't find the element.
> fix(e2e): assertion in e2e example

- src/docs/components/decorators.md
took matthewsteele comment verbatim from here...https://stackoverflow.com/questions/50985239/stenciljs-watch-decorator-not-firing
> feat(docs):add note about @Watch on initial load

- src/docs/components/decorators.md
Hello! 👋
I was browsing the docs and noticed that the `@Component` decorator properties were being displayed as inline text in TypeScript syntax, so I took the liberty to reformat them as a table (which looking at the code seemed that was the intention).
I'm not sure how you'd like to fill the description column, so I skipped it.
Thanks!
Rodrigo
> Fix properties table for Component decorator

- src/docs/testing/unit-testing.md
- remove async from code example that doesn't use any await keywords
> docs(unit-testing): remove async from example

- src/components/landing-page/landing-page.tsx
Fix typo -- replace `Typescript` with `TypeScript` on landing page
> Use correct case for TypeScript

- src/docs/components/api.md
Fixed a typo. 
FROM
Decorators are a pure compiler-time construction used by stencil to **collection** all the metadata...
TO
Decorators are a pure compiler-time construction used by stencil to **collect** all the metadata...
> Update to api.md

- src/docs/tooling/config.md
Btw, it's unclear what the relation is between this file and using a css pre-processor. This is why I left the "can be", but imo should use "is" if the file is **required** for CSS pre-processing via Stencil.
> docs(config): typo

- src/docs/tooling/config.md
I needed this and I figured out thanks to the declarations file.
/cc @adamdbradley
> docs(config): Add preamble doc

- src/docs/testing/e2e-testing.md
This was a head-scratcher for me for weeks! Until someone in the Stencil Slack channel kindly pointed me in the right direction. I had read this page so many times looking for this answer, and found others in the Slack group asking the same.
Adding it here, because at least on our team this was a common complaint against the E2E tests. Some of our components have pretty deep-nested data structures, which means the tests are almost worthless without good mock data.
Open to feedback!
> Add example passing external values to page.$eval

- src/docs/components/templating-and-jsx.md
Clarifies a problem I had that lead to somewhat unexpected behavior. I've seen the branches in a conditional as different siblings and not the very same component. The updated docs make clear how to destroy and recreate components if a conditional switches the branch.
> Working with conditionals and the key-attribute to recreate components

- src/docs/guides/distribution.md
The `main` and `types` field were not accurate to what is actually generated by the `stencil-component-starter`.
I'm not _absolutely_ sure which is correct, but I know, following the documentation, and publishing to NPM... my `dist` definitely does not have a `dist/myname.js` or a `dist/types/index.d.ts`...
> docs: Correct fields in `package.json` example

- src/docs/components/reactive-data.md
Clarifies that this decorator won't fire during the initial load.
> Make it clearer that the Watch decorator don't fire during the initial component load.

- src/docs/guides/style-guide.md
Just a few little nitpicks.
- Remove unnecessary comma, change 'such us' -> 'such as'
- Make 'component' singular so as to agree with the rest of the sentence and the preceding heading: "_The_ name of _the_ class of _the_ component"
- Remove superfluous colon in the plural 'IDEs'
> docs(style-guide): typos, grammar, punctuation

- scripts/markdown-renderer.ts
- src/components.d.ts
- src/components/app-root/app-root.tsx
- src/components/ds-page/ds-page.css
- src/components/ds-page/ds-page.tsx
- src/components/landing-page/landing-page.tsx
- src/components/site-header/site-header.css
- src/components/site-header/site-header.tsx
- src/components/site-top-bar/site-top-bar.css
- src/components/site-top-bar/site-top-bar.tsx
- src/global/style/app.css
- src/global/style/html.css
- src/global/style/hubspot.css
Tweaks some of the copy on the the homepage to be more Design Systems oriented, also adds persistent top bar to link to our blog about web components.
Also had to fix an issue in the markdown script, must be a change in the Prism dependency.
> New copy and top site bar

- src/docs/components/styling.md
Hello there! Big fan of the Stencil project and its motivation.
I was browsing the Styling docs in pursuit of an explanation of the `scoped` option of the `@Component` decorator, and noticed a few lower-case mentions of CSS. So, I took it upon myself to make a few minor improvements to this page.
- Capitalised "CSS" everywhere that it wasn't capitalised in plain text
- Improved grammar where I thought appropriate
- Added a link to MDN's documentation of the `:root` CSS pseudo-class
I didn't create an issue for this, but I can create one if need be.
Please do let me know if anything needs changing.
Cheers! :beers:
> Improved grammar for Styling documentation

- src/docs/components/templating-and-jsx.md
`hostData` function has been replaced with the `Host` element. This updates the JSX documentation to remove reference to `hostData`. See [BREAKING_CHANGES.md](https://github.com/ionic-team/stencil/blob/master/BREAKING_CHANGES.md#hostdata) for more info.
Issue to track this here: https://github.com/ionic-team/stencil-site/issues/404
> docs(JSX): remove reference to hostData

- src/docs/components/styling.md
When following links to the page about "styling" or "styling components" you end up on a page with an h1 "Shadow DOM". This is confusing. The page is about "Styling (Components)" as the title and description in this markdown file also state. The page has two main topics "Shadow DOM" and "CSS Variables", so those should be the h2 level headings. The other sections on Shadow DOM are therefore changed to h3 level headings.
> type(docs): update h1 to match title & menu

- src/docs/guides/style-guide.md
In accordance with https://stenciljs.com/docs/methods#public-methods-must-be-async
> Methods should be async

- src/docs/components/properties.md
Updated 'reflect' @Prop usage example so that it demonstrates property assignment vs attribute display when reflect is set to false.
> Corrected @Prop 'reflect' (false) example

- src/docs/testing/overview.md
This PR corrects a broken on https://stenciljs.com/docs/testing-overview
> Fix broken link in docs

- src/docs/testing/overview.md
This has been asked and referenced on Slack multiple times, and I already posted this config like four times, so I thought it's time to add it to the docs.
The config should probably be tested by someone on Windows, and I can't remember why I set `disableOptimisticBPs`. The tooltip says
> Don't set breakpoints in any file until a sourcemap has been loaded for that file.
and @manucorporat is/was working on getting the sourcemaps working for testing, so we can probably leave it in.
> add info for using a `.vscode/launch.json`

- src/docs/framework-integration/angular.md
- src/docs/framework-integration/react.md
- src/docs/framework-integration/vue.md
Just in case you would like to display the example of framework integrations with the default `dist/loader` aka
```
import { applyPolyfills, defineCustomElements } from 'test-components/dist/loader';
```
instead of
```
import { applyPolyfills, defineCustomElements } from 'test-components/loader';
```
> docs: framework integrations dist/loader

- src/docs/components/properties.md
- src/docs/introduction/faq.md
Addressing a few issues
#490 linking to testing page https://github.com/ionic-team/stencil-site/issues/490
#485 possible typos https://github.com/ionic-team/stencil-site/issues/485
Arguably the biggest issue fixed here is a typo in the title tag, which will appear in search results.
**Fequently Asked Questions** 
I was hesitant about changing FAQ headings but there were grammar issues.
**What browsers does Stencil components work on?**
Also expanding _WC_ to _Web Components_ to be consistent with previous usage.
Lastly should I rewrite my commits to use `type(doc): subject` just noticed this in the contributing guidelines.
> Typos in FAQ copy

- src/assets/docs-structure.json
- src/docs/README.md
- src/docs/guides/local-assets.md
Also added myself to the contributors because the examples from the guide were mostly taken from a message I posted on slack once.
BTW someone didn't commit `components.d.ts` after updating to Stencil 1.5.3 so I had quite a few changes there, but I didn't add it to this commit either (because I don't know when this is going to be merged, and wanted to prevent merge conflicts).
> fix: add local-assets guide to the menu

- src/docs/guides/local-assets.md
Hey guys,
I was totally missing the project context when looking at the example folder hierarchy. I was mixing up `assets` with a folder `assets` in the root of my Stencil project.
Not sure if this for everyone but it would have helped me.
Matt
> add project context

- src/docs/guides/module-bundling.md
I think it's a typo, so fixed it.
`Fortunatelly` -> `Fortunately`
> Fix typo 'Fortunatelly'

- src/docs/introduction/my-first-component.md
Will update the starters now to include said script.
**Edit:** just added another paragraph:
> All components will be generated within the `src/components` folder. Within that, a folder will be created with the same name as the component tag name you provided, and within that folder the files will be generated. It is also possible to specify one or multiple sub-folders to generate the component in.
>
> For example, if you specify `pages/page-home` as the component tag name, the files will be generated in `src/components/pages/page-home`.
> add info about component generator

- src/docs/guides/prerendering.md
Addresses #519 
I wasn't sure how far we want to take the documentation. I also know that the `hydrateDocument` takes a large config object and I'm unsure which each option does. I plan on expanding this PR with more information.
Feedback is very welcome!
> Document How to Use the Hydrate App for SSR

- src/docs/output-targets/docs-json.md
- Adds sections for slots and usage to docs-json
- Removed the _Documenting_ prefix for CSS variables because adding it for slot and usage seemed pretty redundant and looked kinda weird on the ToC
closes #527
> docs(docs-json): add info for slots and usage

- readme.md
Adds a quick instruction to build the docs. Without running `npm run docs` before `npm start`, the docs section of the site doesn't load
closes #536
> chore(readme): add building docs to instructions

- src/docs/config/overview.md
imo, "global" is more conventional, and in fact, is referenced as such in other areas of the site:
https://stenciljs.com/docs/styling#using-css-variables-in-stencil
(we could go the other way as well, just as long as the docs are consistent)
> docs: Correct `globals` -> `global`

- src/assets/docs-structure.json
- src/docs/README.md
- src/docs/output-targets/docs-custom.md
- src/docs/output-targets/overview.md
Adds a docs page for the `docs-custom` output target.
let me know if I missed something, never added a page before :man_shrugging: 
closes #535
> docs(targets): add docs page for docs-custom

- src/docs/output-targets/docs-readme.md
adds docs on:
- custom footers
- different output directory
- strict mode
Not sure if this is the best option for docs. Could also just put dir, strict and footer in a table with a description. I think the version in this PR is clearer, but I'm very open to changing it. 
The only *problem* with having a table is that the default value for footer is pretty long `*Built with [StencilJS](https://stenciljs.com/)*`. Makes it look weird.
Thoughts?
closes #531
> docs(docs-readme): add info on readme output

- src/docs/framework-integration/react.md
Clarifies the main issues that exist with using Custom Elements in React as well as pointing to our Stencil DS Plugins to create an output target for these.
> docs(react): add information about React proxies

- src/docs/components/state.md
Fix documentation by substituting "the" for "to".
> doc: Substitute "the" for "to"

- src/docs/config/extras.md
Based on an [earlier commit](https://github.com/ionic-team/stencil-site/commit/b11071f5f65f5230a6b8ac43b3faff6708c2952f#diff-9b4631c224886721e8787d8e58d94d3e), this seems to have got switched around.
> docs(extra) - typo - mainly used for testing

- src/docs/framework-integration/angular.md
- src/docs/framework-integration/javascript.md
- src/docs/framework-integration/react.md
- src/docs/framework-integration/vue.md
As discussed on Slack, `window` isn't needed anymore to load components with `defineCustomElements`.
Moreover, on Gatsby build, no using `window` is a must, otherwise their prerendering build would fail.
That's why, it's better to display `defineCustomElements` without it.
> feat: window isn't needed anymore to load components with defineCustomElements

- src/docs/guides/style-guide.md
Looks like the `...` in the code sample is breaking the syntax highlighter, so I've put comments on them.
> docs(style-guide): fix code snippet highlighter

- src/docs/framework-integration/react.md
Very small typo fix 👍 Should be good to deploy.
> Typo in React docs

- src/docs/testing/config.md
This change will add a hint explaining that Jest configurations in `package.json` and `jest.config.js` will not be applied. While we're at it, it also fixes two minor punctuation issues.
> docs(testing): add hint for upstream Jest config

- src/docs/output-targets/docs-custom.md
Extend custom docs, add a description for JsonDocs and for JsonDocsComponent. Described common properties that are in the output of stencil custom docs generation.
> docs(Custom Docs): Add Custom Docs Data Model

- src/docs/components/component-lifecycle.md
Removed `componentDidUnload`. Added `connectedCallback`, `disconnectedCallback`, `componentShouldUpdate`, `componentWillRender` and `componentDidRender`.
> docs(lifecycle): update lifecycle chart

- src/docs/components/component-lifecycle.md
fix black background of link in chart on macOS Chrome
> docs(lifecycle): fix black background in chart

- src/components/resources-page/resources-page.css
Added focus styling for easier keyboard navigation.
> docs(resources): tabs don't have focus styling

- src/components/custom-clock.tsx
- src/docs/components/component-lifecycle.md
- src/docs/guides/style-guide.md
Use of `componentDidUnload` is discouraged. It will eventually be removed and it's recommended to use `disconnectedCallback`
@adamdbradley:
> componentDidUnload() is difficult to be accurate 100% of the time since frameworks will sometimes reuse the same "element" it created in the dom, so it's hard for stencil to know if it's a new instance of a component, or that the element was just reused by a framework
> docs: remove `componentDidUnload`

- src/docs/components/events.md
This is a more type-safe way of handling events. Helps writing better tests as well.
> docs(events): use type-safe events

- src/docs/testing/config.md
the device list for puppeteer moved 
from https://github.com/GoogleChrome/puppeteer/blob/master/DeviceDescriptors.js
to https://github.com/puppeteer/puppeteer/blob/main/src/DeviceDescriptors.ts
> Fix url to DeviceDescriptors.js

- src/docs/static-site-generation/basics.md
Returning a Promise from `componentDidLoad` does not impact rendering.
> docs(ssg): fix wrong method name

- src/assets/docs-structure.json
- src/docs/README.md
The page was created in f149dfd but not added to the readme and therefore not accessible.
> docs(publishing): add existing publishing

- src/components/site-menu/site-menu.css
When the search menu is open, code blocks appear on top of the menu. This PR adds a small z-index to the site-menu tp address that.
I believe @fvaldes33 worked on the search feature, so he may be able to determine if this is the most appropriate way to fix this.
Before:
After:
> Fix search menu + code blocks

- src/components/doc-component/doc-component.css
- src/components/search-bar/search-bar.css
- src/components/site-menu/site-menu.css
As I mentioned in the issue, the main content section is too narrow right now. 
It's hard to read code blocks and text lines are too short (kinda newspapers style 😄 ). So, I reduced a sidebar width.
As a side-effect the `dist-custom-elements-bundle` nav item doesn't fit to the container once it's active (bold font increases the size). That's why I prevented word-wrapping and added `ellipsis` to nav elements.
The result:
> docs(ui): Reduce sidebar size

- src/docs/components/component-lifecycle.md
"since these is the method" corrected to "since this is the method". These is referencing multiple methods, but the writers intention was to reference componentWillRender() only
> Fixed a typo at the Rendering State section

- src/docs/components/properties.md
I know it's just an illustrative example, but it wouldn't have worked. If the `newValue` was `null` then `typeof newValue` would be `object`. If `newValue === ''` then `typeof newValue` would be `string`, so it wouldn't ever catch a blank value.
[Confirmed null === "object"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Description)
> docs(properties): fix isBlank code sample

- src/docs/components/reactive-data.md
- some wording tweaks to split sentences up and fix typos
- added @State() decorators to the code examples to make it clear. I've been caught out a few times and then realised I was updating a plain array/object, and not something Stencil was monitoring.
> docs(reactive-data): typos, wording tweaks

- src/docs/components/templating-and-jsx.md
I've seen several people that first hear about the `key` property use the index-parameter of the `map` function as the key like this:
```{ this.aList.map((item, idx) =>
<div key={ idx }></div>
}```
This proposal adds a warning that this parameter is unfit as a `key` and explains why.
> docs(templating): add warning for `key`

- .gitignore
- src/docs/config/extras.md
- src/docs/config/overview.md
Following the release of Stencil v2 and according its [CHANGELOG](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md), extras for legacy browsers and es5 are now opt in options.
This PR reflects these changes to the doc.
> docs: extras and es5 are opt in options

- src/docs/components/events.md
v2 dropped the 'parent' target
> docs: update @Listener target types

- src/docs/components/templating-and-jsx.md
Fix https://github.com/ionic-team/stencil/issues/2667
Fix inconsistencies between usages in the documentation
and ensure best practices as explain in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md) used by [stencil-eslint](https://github.com/ionic-team/stencil-eslint).
also fix typescript errors : 
- JSX element 'input' has no corresponding closing tag.
- Type '(event: UIEvent) => void' is not assignable to type '(event: Event) => void'.
> Update arrow functions to ensure best practices

- src/docs/guides/module-bundling.md
change the verbose from 'explicitally' to 'explicitly'
> docs(guides)

- src/docs/config/extras.md
This event has been renamed to `appload`, and made to be fired regardless of the value of `lifecycleDOMEvents` (see https://github.com/ionic-team/stencil/commits/346736)
I'll leave it to the  Stencil team to decide where best to document the `appload` event itself.
> Remove reference to stencil_appload event in extras config

- src/docs/testing/screenshot-connector.md
Currently ScreenshotConnector is imported but ScreenshotLocalConnector is extended.
Fixed to both use ScreenshotConnector.
> docs: fix extend in screenshot example

- src/docs/output-targets/custom-elements.md
Just correction of the link: 
Before: /output-targets/dist
After: /docs/distribution
> Correction of the 'distribution' page link

- src/docs/testing/unit-testing.md
- Adds Template and documentation about it
- There are more options that are not captured in this document, I'm guessing these are a little out of date
- I've found `Template` particularly helpful when spec testing elements with their props, I don't mind adding an example of that to the docs as well.
> Add Template to NewSpecPage Docs

- src/docs/framework-integration/vue.md
This proposed change adds a hyperlink for faster access to the Vue docs instead of displaying the URL string
> Replace Vue docs URL string with hyperlink

- src/docs/components/component-lifecycle.md
Changes:
- clarify why connectedCallback usage is a best practice
Testing:
- Ran `npm ci` locally, since changes do not require package updates
- Ran `npm run docs && npm start`
- Navigated to http://localhost:3354/docs/component-lifecycle#connectedcallback to verify output
> docs(lifecycle): clarify connectedCallback usage

- src/components/app-root/app-root.tsx
Changes:
- auto-generate the correct year for the copyright
Testing:
```
$  npm run build
$ npm run docs
$  npm start
```
Navigated to [the docs](http://localhost:3333/docs/introduction) to verify the output was correct
> chore(docs) update copyright in footer

- src/docs/components/component-lifecycle.md
This replaces the warning in the Stencil compiler, see:
https://github.com/ionic-team/stencil/pull/2947
> Explain to setup the state before componentDidLoad()

- src/components/resources-page/resources-data.ts
- src/docs/introduction/faq.md
- src/docs/introduction/my-first-component.md
- The repository https://github.com/jepiqueau/stencil-flip-images doesn't exist any more, and there wasn't a replacement to find during a quick research, so I've removed the link in total
- The blog entry "How Lazy-Loading Web Components Work with Stencil" ([/blog/how-lazy-loading-web-components-work](https://ionicframework.com/blog/how-lazy-loading-web-components-work)) doesn't exist any more – it must have been either removed intentionally or hasn't been migrated to the new home of the blog entries on https://ionicframework.com/. So I've added an archived version of that page as the link target as I still expect that content to be relevant.
- The `master` branch of the https://github.com/ionic-team/ionic/ repository has been renamed to `main`, so we had to change the related link to …
> refactor(docs): corrected some links

- src/docs/config/extras.md
Add documentation for https://github.com/ionic-team/stencil/pull/3047
> docs(config): add documentation for scopedSlotTextContentFix

- src/docs/components/component.md
add documentation to configure the `shadow` property using the
`{ delegatesFocus: boolean }` object literal instead of a boolean
> docs(component): add documentation for delegatesFocus

- src/docs/components/properties.md
add documentation around types used by @props and their visibility
STENCIL-222: bug: @Prop can't work with typescript's Type alias
> docs(props): add documentation for exporting prop types

- src/docs/introduction/faq.md
add information to the site around:
- the currently supported version of stencil
- how and when breaking changes will occur
- a link to the releases page
- information that we do not support v0 and v1
> docs(versioning): add documentation around versioning & support

- src/docs/framework-integration/angular.md
- The documentation for Angular framework integration mentions `React` in some places where it should be `Angular` instead.
> docs(angular): replace `React` with `Angular`

- src/docs/framework-integration/react.md
this pr makes a few minor adjustments to the react wrapper docs after running through them myself.  most notably, it:
- attempts to reinforce the React Component Library:
- wraps Stencil components
- holds our React wrapper components
- making the linking process a little easier by:
- having folks clone the stencil ds react template to a directory whose name matches the template's `package.json#name` value
- avoid having to switch directories by running `npm build` before `npm link`
- clarify how exporting components from the React Component Library works (mostly that it is not needed if you use the template)
> docs(react): update react wrapper docs

- src/docs/testing/overview.md
state the versions of jest and puppeteer that are supported by stencil. this is the 'required' work for supporting Jest 27+. however, i took an initial stab at some rework of the testing overview page, but by no means is it "good enough" for us to mark it off our sheet of pages we want to improve. the test configuration & IDE integration could certainly use a little more love, but I think it's in a slightly better state than where it was/is today
> docs(testing): add explicit mention of testing lib versions

- src/docs/framework-integration/angular.md
If we had the `.ts`, it's not possible to build the angular app
> Fix export .ts

- src/docs/components/properties.md
the example fixed was using syntax that represented passing a string
value into the component's prop, rather than a boolean.
there's an active rewrite occurring for this page, but this is a 'quick
win' we can achieve while that occurs
> docs(props): use proper syntax for JSX boolean example

- src/docs/framework-integration/react.md
update react wrapper output directory structure to show
`react-component-lib/` is a child directory of `stencil-generated`
> docs(react): update react wrapper output dirs

- src/docs/output-targets/custom-elements.md
- src/docs/output-targets/dist.md
add an additional note that the `dist-custom-elements-build` is deprecated when comparing it against `dist-custom-elements`
> docs(custom-elements): clarify CEB is deprecated

- src/docs/introduction/getting-started.md
explain the output of the `npx init stencil` command, to try to bridge
the gap between running the command and getting started/running with
stencil for the first time.
there's some duplication of information here. ie if we were to change
the cli output, we'd need to change the instructions here as well, which
as a landing point of sorts of our docs, i'm looking for
feedback/thoughts here
i personally don't _love_ the ordering of the output, this may make for a
good JEDI days quick project. To me it makes more sense to output the 
'next steps' (`cd` to your project dir, `npm i`) then talking about running
`npm start`, `npm run build`, etc.
fixes: https://github.com/ionic-team/stencil-site/issues/817
(or attempts to)
> docs(getting-started): explain cli output

- src/docs/guides/style-guide.md
❌ Incorrect name: `componentShouldRender`
✅ Correct name: `componentShouldUpdate`
> Fix incorrect name of Component Lifecycle Method

- src/docs/components/methods.md
- src/docs/components/properties.md
There is a typo in the docs: It should be "JavaScript" instead of "JavaScrip"
> fix: fix typo

- src/docs/components/api.md
- src/docs/components/component-lifecycle.md
- src/docs/components/state.md
this commit updates the documentation for the `@State()` decorator. the
goal of this commit is to make the documentation clearer around the
decorator's usage, while providing additional examples.
> docs(state): refactor state prop documentation 

- src/docs/components/properties.md
this commit expands the 'advanced prop types' section to contain
information on how stencil interprets the `any` type in TypeScript, as
well as optional class members (e.g. `isComplete?: boolean`)
each of the examples has been tested locally in a stencil v2.14.0
project.
STENCIL-158: Investigate Stencil Prop narrowing
> docs(props): add any and optional type info 

- src/docs/framework-integration/angular.md
Updates the usage instructions for setting up the `@stencil/angular-output-target` as found here: https://stenciljs.com/docs/angular#what-is-the-best-format-to-write-event-names
- Fixes an incorrect implementation detail where Angular components were being added to the `imports` array (which is not correct for Angular modules).
- Uses `npx` to avoid installing global dependencies
- Removes npm vs. yarn syntax (developers are commonly aware)
- Uses less verbose language for instructions
- Specifies the advantages of using the component wrappers over the vanilla web components
Does not modify language of FAQ and API. Those sections should be updated at a later date.
> docs(angular-framework-integration): set-up instructions

- src/assets/docs-structure.json
- src/docs/README.md
- src/docs/introduction/faq.md
- src/docs/reference/support-policy.md
- src/docs/reference/versioning.md
this pr adds 2 pages to our documentation:
1. a support policy
2. an explainer on how Stencil shall use semver
both documents are heavily borrowed from the Ionic
framework, where the former is borrowed from
https://ionicframework.com/docs/reference/support
and the latter from https://ionicframework.com/docs/reference/versioning
> docs(support): add support policy + versioning docs

- src/docs/introduction/getting-started.md
remove warning notice for having to run npm install. this should
be self explanatory now that we've fixed the flow of this section
> docs(getting-started): remove warning notice

- src/docs/testing/overview.md
this commit removes test library support information for jest 
and puppeteer, and redirects viewers to the Stencil support policy.
this allows us to have one source of truth for which libraries we are
actively supporting
> docs(testing): remove duplicate test library information

- src/docs/reference/support-policy.md
- src/docs/reference/versioning.md
~Depends on: #842, please do not merge yet~ 
add typescript support section to the support policy. this section
attempts to explain:
- that typescript comes bundled with the stencil compiler
- the release cadence of the typescript team
- how and when the stencil team will update typescript
- acknowledge breaking changes occur in minor versions of typescript
this commit also updates the versioning page's minor release section
to link back to this policy
STENCIL-205 Add Support Policy for Stencil Major Version Strategies
> docs(support): add typescript support details

- src/docs/output-targets/custom-elements.md
this commit adds documentation for the `generateTypeDeclarations` flag
on the `dist-custom-elements` output target
See https://github.com/ionic-team/stencil/pull/3270 for implementation details
> docs(custom-elements): add generateTypeDeclarations doc

- src/docs/components/component.md
The `assetsDir` parameter to `@Component` was deprecated some time ago,
and for stencil v3 we will remove backwards compatibility for it. This
commit accordingly removes references to it from the docs.
STENCIL-410
> docs(component): remove reference to deprecated `assetsDir` option

- src/docs/output-targets/custom-elements.md
It looks like some documentation got copy-pasted from the
`dist-dist-custom-elements-bundle` documentation, but as far as I can
tell it does not apply to the `dist-custom-elements` output target.
This just edits things a bit to clarify 1) that the component files are
written to a directory (`dist/components`) and 2) that each file written
will export a single component.
> docs(dist): fix some confusing documentation for `dist-custom-elements`

- vercel.json
when navigating to https://stenciljs.com/docs/ (with the trailing
slash), the site complains we cannot find the page the user is looking
for. this commit updates the permanent redirect for '/docs' to accept
both `/docs/` and `/docs` for performing a redirect to the introduction
page of the docs
example
testing:
navigate to the Vercel preview associated with this PR:
- add `/docs/` to the URL, see the redirect work
- add `/docs` to the URL, see the  existing redirect work
> fix(redirect): redirect /docs/ to intro page

- src/components/resources-page/resources-page.css
- src/components/resources-page/resources-page.tsx
as a part of an initiative to clearly define the projects that the
stencil team is maintaining, the team is going through and archiving
projects that will no longer be maintained by ionic nor by the
community. one such example is https://github.com/ionic-team/stencil-present
before we archive that project, i'd like to remove it from the
resources/ page on the stencil site.
in removing the stencil component that wrapped the iframe, any css
classes that were removed were searched for in the codebase. any classes
that were only used for the removed component were also removed
> docs(resources): remove stencil announcement presentation

- src/docs/output-targets/custom-elements.md
this commit moves a statement about adding `@stencil/core` as
a dependency in `package.json` down. otherwise, it looks like we're
missing an example
fixes: #885
> docs(custom-elements): clarify distribution example

- src/docs/output-targets/custom-elements.md
The documentation for the `autoDefineCustomElements` wasn't _quite_
accurate. This clarifies that what the flag does right now for the
`dist-custom-elements` output target is basically add a call to the
module for each component for that components `defineCustomElement`
function.
> docs(dist-custom-elements): update docs for autoDefineCustomElements option

- src/docs/config/extras.md
this commit adds the documentation for the `experimentalImportInjection`
configuration flag
STENCIL-339: Integrate Bundler Feature into Stencil
this commit is tied to: https://github.com/ionic-team/stencil/pull/3364 & https://github.com/ionic-team/stencil/pull/3349
> docs(extras): add documentation for experimentalImportInjection

- src/docs/output-targets/docs-readme.md
The documentation is currently out of date, describing the use of a
`--docs-readme` CLI flag which Stencil does not support. However, the
`--docs` CLI flag does what the docs say that the `--docs-readme` flag
should do, so we can point the user towards that instead.
This was reported in ionic-team/stencil#3405
STENCIL-472
> docs(docs-readme): update docs-readme description of alternative CLI flag

- src/docs/guides/publishing.md
Since we [don't recommend](https://stenciljs.com/docs/distribution) `dist` to be tracked by version control, but expose it in package.json, people like me who are new get confused at the first glance. So thought describing the `files` property will make it clear that though we don't add `dist` to version control, publish it to NPM.
> Add info about the files property in package.json

- src/docs/introduction/getting-started.md
update the `npm init stencil` text after releasing v3.0.0 of the
create-stencil cli (which moved the app starter to the community)
> docs(started): update starter text

- src/assets/docs-structure.json
- src/docs/README.md
- src/docs/output-targets/docs-vscode.md
- src/docs/output-targets/overview.md
this commit adds the initial documentation for using the `docs-vscode`
output target
> docs(output-targets): add vscode documentation

- src/docs/framework-integration/vue.md
this commit adds an additional change to the bootstrapping process
of a user's vue library, to ensure that the `main` field in `package.json`
is set to `lib/index.js`.
the reason for this change is that when users run `lerna create PROJ-NAME`,
by default, the `main` field takes on the value of 'PROJ-NAME', which isn't the
entrypoint we want folks to be using (I don't think)
> docs(vue): update vue library bootstrapping

- src/docs/testing/config.md
Clarifies where (in which file) these testing settings go.
> refer to stencil.config.ts in testing config

- src/docs/output-targets/custom-elements.md
This adds documentation of the change to the `dist-custom-elements`
output target introduced in ionic-team/stencil#3368. That PR adds
a re-export of all the built components from the `index.js` file,
which will support some existing workflows based on the
`dist-custom-elements-bundle` output target.
> docs(dist-custom-elements): update documentation to reflect index.js changes

- src/docs/guides/hydrate-app.md
Just some cleanup to clear up confusing wording and explanations here,
format things a little bit more cleanly, and so on.
> docs(hydrate): clean up the docs for the hydrate app output target

- src/docs/framework-integration/react.md
this commit updates the supported version of react to
v16.7.0. our current framework wrapper implementation 
declares a minimum of v16.7.0 (https://github.com/ionic-team/stencil-ds-output-targets/blob/bc8878f5ccd1890ec378a57f8e69a44b15213102/packages/react-output-target/package.json#L39-L43).
this commit aligns the dependencies of the framework wrapper
and the documentation.
> docs(react): update supported react version to 16.7

- src/docs/config/plugins.md
**Do not merge - I need to complete the postcss migration first **
this commit updates the urls/names of various stencil-related css
plugins. specifically, it is a result of our investigation as to how to
handle moving css packages to the community (or archive them) as a part
of stencil-478.
in this commit:
- @stencil/postcss is renamed to @stencil-community/postcss to signify
moving that package to the community
- @stencil/less and @stencil/stylus are marked as deprecated, as there
was no interest in maintaining them from our call to action
> docs(styles): update references to css plugins

- src/docs/framework-integration/vue.md
prior to this commit, installing typescript & node types read a
little funky. this commit updates the comments in that code block
to hopefully make it a little clearer
> docs(vue): clarify installing typescript section

- vercel.json
this commit updates the redirect for https://stenciljs.com/blog/ (note the
trailing slash) to redirect to the Ionic blog.
STENCIL-287: Fixup Blog Redirect
> docs(blog): redirect on blog/

- src/docs/output-targets/dist.md
This commit adds documentation to the `dist` output target docs for the `transformAliasedImportPathsInCollection` config option
> docs(output-targets): docs for `transformAliasedImportPaths` on `dist`

- src/docs/reference/support-policy.md
this commit adds a row to the typescript support table to specify the
update to typescript 4.7 in an upcoming version of stencil. see
ionic-team/stencil/pull/3530 for the implementation
STENCIL-435: Upgrade TypeScript to v4.7
tested locally to verify the table was still properly formatted:
> docs(support): add typescript 4.7 to table

- src/docs/output-targets/custom-elements.md
This commit modifies the docs for `dist-custom-elements` to add documentation for the `customElementsExportBehavior` config option
> feat(output-targets): add section for `customElementsExportBehavior`

- src/docs/components/properties.md
this commit adds examples for props that are marked as `mutable: true` at declaration time. its point/focus is to demonstrate that the _reference_ can be mutated within stencil without causing a warning, but mutable operations such as `Array.prototype.push` will not trigger a render
> docs(props): add mutable:true examples for arrays, obj

- src/docs/components/reactive-data.md
this commit updates the documentation for `@Watch`. it primarily focuses
on discussing how to get the decorator to fire for class members that
are objects/arrays in order to provide clarification for how stencil
compares old/new values (by reference).
minor copy edits throughout the page have been made to improve clarity
> docs(reactive-data): update @watch documentation 

- src/docs/config/overview.md
- src/docs/output-targets/custom-elements.md
Starting to add some callouts around the impacts `externalRuntime` has on the `dist-custom-elements` output target. There isn't a lot here, but I couldn't think of a good overarching description that ties these behaviors together to add more context.
> docs(custom-elements): add externalRuntime config option 

- src/docs/config/overview.md
- src/docs/output-targets/custom-elements.md
This commit rewrites and restructures portions of the dist-custom-elements output target docs. Additional config options are documented, and more context for when/how to use the target has been added.
> docs(output-targets): update dist-custom-elements docs

- src/docs/output-targets/docs-custom.md
this commit adds the 'overview' field on the `JsonDocsComponent` model, introduced in https://github.com/ionic-team/stencil/pull/3766. it also updates the description of the 'docs' field in the same model to better reflect its functionality
> docs(docs-custom): add overview field

- src/docs/introduction/upgrading-to-stencil-three.md
this commit adds a note to the documentation stating that v3.0.0 is still a work in progress, to avoid confusion should someone stumble upon this page
> docs(upgrade): add v3 alpha note

- src/docs/reference/support-policy.md
this commit updates the typescript/stencil support table to account for typescript v4.8.4 support.
this commit is dependent on https://github.com/ionic-team/stencil/pull/3743
> docs(typescript): add v4.8.4 to ts support table

- src/docs/introduction/upgrading-to-stencil-three.md
this commit ports the documentation changes from https://github.com/ionic-team/stencil/pull/3810 (https://github.com/ionic-team/stencil/commit/22c74241ebb471123680d6629d7fa9c17b86c897) to the v2 version of the stencil site
> docs(breaking_changes): port puppeteer 19 support to v2 site

- src/docs/introduction/upgrading-to-stencil-three.md
this commit updates the upgrade guide for the v2 version of the site. specifically, it changes the `npm install` scripts in the 'Getting Started' section to use teh `v3-next` tag, rather than a semver compliant version (`3`). we do this as v3 has not been officially released, making the script useless.
instead, we use an intentionally vague tag number that allows the dev team to update v3-next behind the scenes (from v3.0.0-alpha.0 to v3.0.0-alpha.1, etc.) without having to change the documentation for every release
> docs(v3-upgrade): update npm tag for v3 prereleases

- src/docs/static-site-generation/meta.md
this commit designates stencil helmet as deprecated. since links to this
section of the docs may still exist, in conjunction with the fact that
vercel does not allow redirects using anchor tags, we keep the section
in the docs, but link to the github page (which will soon see the
project marked as deprecated)
newlines were added to the markdown to improve "readability" of the
page. (although that word leaves a sour taste in my mouth)
> docs(helmet): deprecate stencil helmet 

- src/docs/output-targets/custom-elements.md
Removes the section on `inlineDynamicImports` from `dist-custom-elements` docs.
Related to [Stencil PR #3897](https://github.com/ionic-team/stencil/pull/3897)
> docs(custom-elements): remove inlineDynamicImports option section

- src/docs/config/extras.md
This updates the documentation for the `dynamicImportShim` field to indicate that it's been deprecated in Stencil V3.
> docs(extras): update documentation to deprecate dynamicImportShim

- src/docs/config/extras.md
This updates the documentation for the `cssVarsShim` field to indicate that it's been deprecated in Stencil V3.
> docs(extras): update docs to deprecate `cssVarsShim`

- src/docs/introduction/upgrading-to-stencil-three.md
This adds a note to the v3 upgrade guide about deprecating `extras.shadowDomShim`.
NOTE: this PR has #948 as its base.
> docs(v3-upgrade): add note about deprecating `shadowDomShim`

- src/docs/introduction/upgrading-to-stencil-three.md
This adds a note to the v3 upgrade guide about deprecating `extras.cssVarShim`.
**NOTE**: this PR has https://github.com/ionic-team/stencil-site/pull/948 as its base.
> docs(v3-upgrade): add note about deprecating `cssVarsShim`

- src/docs/config/extras.md
This updates the documentation for `safari10` to indicate that it's been deprecated in Stencil v3.0.0.
> docs(extras): update docs to reflect deprecation of safari10

- src/docs/introduction/upgrading-to-stencil-three.md
This adds a note to the v3 ugprade guide about deprecating `extras.safari10`.
> docs(v3-upgrade): add note about deprecating safari10

- src/docs/introduction/upgrading-to-stencil-three.md
this commit changes the codeblock for installing `@stencil/core@v3-next` to use inline, monospaced font. this is due to a bug in the hydration of code blocks that include forward slashes. today, a code block with the original content, '@stencil/core@v3-next', may be rendered as:
```
@stencil/core@v3-nextcore@v3-next
```
where the content following the slash ('core@v3-next') is added as an additional text node in the DOM (without any line breaks).
with the upcoming migration to docusaurus for the stencil site, we choose to 'patch' this by moving away from the text block. it's slightly less readable, but ensures the install command is always correct
> docs(v3): format codeblock for install command

- src/docs/introduction/upgrading-to-stencil-three.md
This commit adds a section to the v3 migration guide for the removal of `inlineDynamicImports` from `dist-custom-elements`
Related to [Stencil PR #3897](https://github.com/ionic-team/stencil/pull/3897)
> feat(docs): removal of inlineDynamicImports to migration guide

- src/docs/introduction/upgrading-to-stencil-three.md
first commit: This starts a new section in the v3 upgrade docs for the fields in `config.extras` which will be marked as deprecated in Stencil v3. This first commit includes notes about the `dynamicImportShim` field. See https://github.com/ionic-team/stencil/pull/3895
> docs(v3-upgrade): add note about deprecating fields in extras

- src/docs/introduction/upgrading-to-stencil-three.md
this commit updates the notification stating that stencil v3 is in beta, now that beta.0 has been released (https://github.com/ionic-team/stencil/releases/tag/v3.0.0-beta.0)
> docs(v3): updated v3 version designation to beta

- src/docs/framework-integration/react.md
Since the `@stencil/react-output-target` is a build-time compiler tool it should be a dev dependency.
closes: https://github.com/ionic-team/stencil-site/issues/959
> fix: React bindings should be installed as a dev dependency in example

- src/docs/reference/support-policy.md
this commit adds typescript 4.9 to the support table
~this PR has the commit for TS 4.8 support in it as well. I built this branch atop #934, to avoid merge conflicts in the future. this first commit will be gone on Monday after I merge the 4.8 PR.~ rebased following the v2.20 release
> docs(support): add typescript 4.9 to support table 

- src/docs/guides/csp-nonce.md
This commit updates the CSP guide with the new `meta` tag fallback rather than using `window`
> docs(guides): update csp guide for meta tag fallback

- src/docs/guides/style-guide.md
this commit updates the reference to the stencil eslint plugin to make note that the package will be owned by the community
> chore(lint): update eslint reference

- src/docs/components/reactive-data.md
@Watch decorates passes a third parameter, the name of the property that is changed. Very handy when you are using stencil-store and want to update the store accordingly when the initial prop/state changes.
> Incomplete documentation.

- src/docs/components/properties.md
this commit updates the properties page to state that setting component's `@Prop()` decorated member that is of type `Object` cannot be set via an attribute
Closes: https://github.com/ionic-team/stencil-site/issues/891
> docs(props): state limitation of attributes + objects

- src/docs/introduction/upgrading-to-stencil-three.md
This commit adds a section to the v3 migration guide for the Stencil framework wrapper output targets. In this section, it talks about the impacts `customElementsExportBehavior` has on the framework wrappers and how to achieve the same behavior as in Stencil 2
Closes #977
> feat(v3-migration-guide): add section for framework wrappers

- docs/guides/module-bundling.md
- docs/introduction/03-getting-started.md
- docs/introduction/04-my-first-component.md
- docs/introduction/upgrading-to-stencil-three.md
- versioned_docs/version-v2/guides/module-bundling.md
- versioned_docs/version-v2/introduction/03-getting-started.md
- versioned_docs/version-v2/introduction/04-my-first-component.md
- versioned_docs/version-v2/introduction/upgrading-to-stencil-three.md
- versioned_docs/version-v3.0/guides/module-bundling.md
- versioned_docs/version-v3.0/introduction/03-getting-started.md
- versioned_docs/version-v3.0/introduction/04-my-first-component.md
- versioned_docs/version-v3.0/introduction/upgrading-to-stencil-three.md
This adds the little `npm2yarn` directive on a few code blocks where we tell the user to run comands.
> chore(docs): add npm2yarn directives to code blocks in a few places

- .gitignore
this commit adds directories created by code editors to the gitignore to prevent them from being pushed to the repo
> chore(git): add editors to gitignore

- docs/guides/style-guide.md
- versioned_docs/version-v2/guides/style-guide.md
- versioned_docs/version-v3.0/guides/style-guide.md
this commit fixes the references to `@stencil-community/eslint-plugin` that were originally applied in
https://github.com/ionic-team/stencil-site/pull/968 and accidentally lost in https://github.com/ionic-team/stencil-site/pull/902
> docs(style): update eslint references

- docusaurus.config.js
this commit updates the logic for excluding docs to account for docs that are in versioned docs directories. prior to this commit, docs in the v2 and v3.0 directories wouldn't be excluded, causing for an incorrect sidebar to be generated
> fix(docs-hiding): update logic for excluding docs

- docs/components/templating-and-jsx.md
- versioned_docs/version-v2/components/templating-and-jsx.md
- versioned_docs/version-v3.0/components/templating-and-jsx.md
this commit restores some of the content created in https://github.com/ionic-team/stencil-site/pull/915 that was accidentally lost in
https://github.com/ionic-team/stencil-site/pull/902.
> docs(jsx): restore pre-docusaurus jsx text

- docs/reference/browser-support.md
- src/css/bs-chart.scss
- src/css/custom.scss
- src/css/headline.css
- versioned_docs/version-v2/reference/browser-support.md
- versioned_docs/version-v3.0/reference/browser-support.md
this is a quick-and-dirty restoration of the styling on the browser support page, where we had some custom stuff before. The web team should go over this in more detail at some point, but this at least gets us away from some unstyled text that is there atm.
> fix(browser-support): restore styling of browser-support page

- docs/components/component-lifecycle.md
- versioned_docs/version-v2/components/component-lifecycle.md
- versioned_docs/version-v3.0/components/component-lifecycle.md
in the migration to docusaurus, the live clock example broke. this commit temporarily removes it while we work through the best way to configure/load the stencil component in the future (that way the docs don't appear broken)
relates to: https://github.com/ionic-team/stencil-site/issues/1010, although it does _not_ close the issue
> docs(lifecycle): temp remove clock example

- docs/components/component-lifecycle.md
- src/components/LifecycleMethodsChart.module.css
- src/components/LifecycleMethodsChart.tsx
- versioned_docs/version-v2/components/component-lifecycle.md
- versioned_docs/version-v3.0/components/component-lifecycle.md
We previously had an interactive chart of the different component lifecycle methods on the corresponding page which was implemented as a Stencil component. This ports that component to React, making the minimal set of changes which I believe are necessary to get it working.
Check that:
- you can see the chart on the `docs/component-lifecycle` page for all three versions
- the hovering styling effect works as it used to in the Stencil-based implementation
- the links in the chart all point to the right page (i.e. the link to the `@Watch` documentation should point to that page for the version that you're currently looking at)
> docs(component): port component lifecycle chart to React

- docs/components/host-element.md
- versioned_docs/version-v2/components/host-element.md
- versioned_docs/version-v3.0/components/host-element.md
This commit adds a small snippet to the host element docs to show using TS's definite assignment assertion modifiers for class member initialization. Closes [#2660](https://github.com/ionic-team/stencil/issues/2660)
> docs(host-element): add snippet for definite assignment assertion

- docs/guides/csp-nonce.md
- versioned_docs/version-v2/guides/csp-nonce.md
- versioned_docs/version-v3.0/guides/csp-nonce.md
- Removes a reference to `autoDefineCustomElements` in the CSP nonce guide in favor of the new `customElementsExportBehavior` option
- Removes some redundant wording in older docs versions
> docs(csp-guide): updates guide to remove `autoDefineCustomElements` ref

- docs/introduction/upgrading-to-stencil-three.md
- versioned_docs/version-v2/introduction/upgrading-to-stencil-three.md
- versioned_docs/version-v3.0/introduction/upgrading-to-stencil-three.md
this commit adds a table with the minimum supported versions (or, strongly recommeneded versions) of other `@stencil` scoped packages to upgrade
> docs(v3): add minimum supported versions for other stencil packages

- docs/guides/design-systems.md
- docs/reference/support-policy.md
- versioned_docs/version-v2/guides/design-systems.md
- versioned_docs/version-v2/reference/support-policy.md
- versioned_docs/version-v3.0/guides/design-systems.md
- versioned_docs/version-v3.0/reference/support-policy.md
Removes enterprise related links/language from the docs:
- Removes the "Enterprise support" links from the design system page(s)
- Updates the text copy in the extended enterprise support section and support policy
> chore: remove enterprise links

- docs/components/component.md
- versioned_docs/version-v2/components/component.md
- versioned_docs/version-v3.0/components/component.md
this commit attempts to pull the content out of the existing
`@Component()` documentation (currently in a JSDoc block) to improve the
searchability of options, and begin to unify how we display said
options with pages such as the dist-custom-elements output target.
additional examples have been added to clarify usage of the options in
`@Component()`
**All changes are currently only in the 'next' version**
**Current Asks**
- ✔️ My highest priority here is format - does this look/feel OK?
-  ✔️ Second to that is content - does that seem right?
- Take a look at v2 docs, I propagated the changes there (and to v3.0, but they're the same as 'next'). I added a small section for `assetsDir`, which we removed in v3.0.0
✔️ Once we have those two down, I'll propagate this to the other pages
**TODO** …
> docs(component): pull options out of jsdoc

- .github/dependabot.yml
this commit adds `@mdx-js/react` v2+ to the dependabot ignore list. at the time of this writing, we're on the latest version of docusaurus, which does not support the latest version of mdx. ignore it so dependabot does not keep rebasing an upgrade pr for us
Supersedes: https://github.com/ionic-team/stencil-site/pull/1030
> chore(github): add mdx-js to dependabot ignore list

- docs/testing/01-overview.md
- versioned_docs/version-v2/testing/01-overview.md
- versioned_docs/version-v3.0/testing/01-overview.md
this commit updates the vscode launch configuration to one that works
slightly better between different operating systems. VS Code variables
have been updated to minimize the amount of differences required between
MacOS and Windows. a special tip callout has been created to direct
Windows users to the correct program configuration
Closes: https://github.com/ionic-team/stencil-site/issues/486
Relates to: https://github.com/ionic-team/stencil/issues/2756
> docs(testing): update vscode launch configuration

- docs/components/reactive-data.md
- versioned_docs/version-v2/components/reactive-data.md
- versioned_docs/version-v3.0/components/reactive-data.md
- add missing space replacing "are-render" with "a re-render"
https://github.com/ionic-team/stencil-site/issues/1042
> Update reactive-data.md | Documentation typo

- docs/config/extras.md
- versioned_docs/version-v3.0/config/extras.md
this commit updates the extras config example to use the '__deprecated__' prefix for deprecated fields (starting with v3.0.0)
> docs(extras): update extras config example

- docs/reference/support-policy.md
- versioned_docs/version-v2/reference/support-policy.md
- versioned_docs/version-v3.0/reference/support-policy.md
this commit designates node 18 support in stencil 3. it also adds a
footnote that stencil 2 may be able to support node 18, as no known
issues have been reported when using the two.
the v2 version of the docs are slightly different from v3.0 and 'next',
as it omits the v3 row.
Images of Changes for each Version (see screenshot, version in header of site):
> docs(support): add node 18 to support policy

- docs/framework-integration/angular.md
- versioned_docs/version-v2/framework-integration/angular.md
- versioned_docs/version-v3.0/framework-integration/angular.md
Adds a section header for "defining custom elements" to the Angular guide. This aligns the "setup" sections of all three guides to have (mostly) the same structure.
> docs(angular): add "defining custom elements" section header

- docs/config/01-overview.md
This adds documentation of the new `transformAliasedImportPaths` option, added to Stencil in https://github.com/ionic-team/stencil/pull/4042/.
> feat(config): Add documentation of `transformAliasedImportPaths` option

- CONTRIBUTING.md
this commit updates our contributing guide to align with the docusaurus versioning scheme that the site is now using. it updates the commands folks are expected to run, and provides details as to how to navigate the site/change the correct files for the version of stencil they are using
> chore(contributing): update contributing for docusaurus

- package.json
this commit adds volta to the project, allowing for the team to be using a consistent version of node/npm when working on the site. when volta is on the developers PATH, the version of npm/node will be set automatically for them. this is being done to align with the rest of the stencil developer environments found in stencil, stencil-sass, etc
> chore(infra): add volta to the project

- package-lock.json
I believe when #1027 was merged the `package-lock.json` for `ionic-preset/` was changed (https://github.com/ionic-team/stencil-site/pull/1027/files#diff-bec91fb3a2296d91b0b92b2b5bcb3f896c2c2a1f7da8bb3a399b76e71b4d257d) but those changes didn't make their way to the root `package-lock.json`, so doing an `npm ci` would result in the following error:
This PR is just the result of running `npm i` in the root of the repo.
I'm not sure if there's a dependabot setting that can make it smarter about things like this.
Noticed when reviewing #1056
> chore(): regenerate package-lock.json

- versioned_docs/version-v2/introduction/03-getting-started.md
- versioned_docs/version-v3.0/introduction/03-getting-started.md
- versioned_docs/version-v3.1/introduction/03-getting-started.md
this commit propagates the changes that @alicewriteswrongs suggested in becad3b08bf416b5e278ea9a8dade1df88308055 (#1049) to the versioned_docs versions of the tutorial. i'm not quite sure how these didn't get propagated during the original pr, most likely an order of operations issue on @rwaskiewicz's end
> docs(getting-started): sync next folder with versioned docs

- docs/introduction/03-getting-started.md
- versioned_docs/version-v2/introduction/03-getting-started.md
- versioned_docs/version-v3.0/introduction/03-getting-started.md
- versioned_docs/version-v3.1/introduction/03-getting-started.md
this commit updates the getting started documentation to clearly state that `npx` will fetch the package for you, in an attempt to make it clear how stencil can be install globally
Closes: https://github.com/ionic-team/stencil/issues/2189
> docs(getting-started): make global install explicit

- package.json
this commit removes the 'mv www' from the build.ci command. sometime between 2023.03.15 and 2023.03.16, vercel deploys began to fail due to the `build/` directory being missing after build. the build passes locally, which gives cause to something changing on the vercel side as far as this check goes. this `mv` is believed to be a remnant of the old stencil site + transition to docusaurus, and no longer needed
The deploy for the[ first commit](https://vercel.com/ionic/stencil-docs/Bvo5ZukbDpnRCdtCv53evzCyRvJR) errors:
```
[14:36:07.911] Running build in San Francisco, USA (West) – sfo1
[14:36:07.967] Cloning github.com/ionic-team/stencil-site (Branch: rwaskiewicz/fix-ci-www-rm-mv, Commit: a20bfb3)
[14:36:08.227] Previous build caches not available
[14:36:09.148] Cloning completed: 1.181s …
```
> fix(ci): fix deploys, remove mv command

- docs/components/styling.md
- docs/guides/design-systems.md
- docs/introduction/01-overview.md
- docs/reference/faq.md
- versioned_docs/version-v3.0/components/styling.md
- versioned_docs/version-v3.0/guides/design-systems.md
- versioned_docs/version-v3.0/introduction/01-overview.md
- versioned_docs/version-v3.0/reference/faq.md
- versioned_docs/version-v3.1/components/styling.md
- versioned_docs/version-v3.1/guides/design-systems.md
- versioned_docs/version-v3.1/introduction/01-overview.md
- versioned_docs/version-v3.1/reference/faq.md
- versioned_docs/version-v3.2/components/styling.md
- versioned_docs/version-v3.2/guides/design-systems.md
- versioned_docs/version-v3.2/introduction/01-overview.md
- versioned_docs/version-v3.2/reference/faq.md
this commit updates the copy for all v3+ based pages to emphasize stencil's role in component libraries, rather than design systems as a whole. stencil solves a crucial role for design systems, the creation of components and patterns. we emphasize that aspect of it in these changes
> docs(purpose): update copy around design systems

- docs/components/api.md
- versioned_docs/version-v2/components/api.md
- versioned_docs/version-v3.0/components/api.md
- versioned_docs/version-v3.1/components/api.md
- versioned_docs/version-v3.2/components/api.md
Adds documentation for `componentOnReady()` to the component API section of the docs.
> add componentOnReady to API docs

- docs/framework-integration/angular.md
- versioned_docs/version-v3.0/framework-integration/angular.md
- versioned_docs/version-v3.1/framework-integration/angular.md
- versioned_docs/version-v3.2/framework-integration/angular.md
Adds documentation for the `includeSingleComponentAngularModules` option of `@stencil/angular-output-target`.
> docs(angular-output-target): includeSingleComponentAngularModules option

- docs/framework-integration/angular.md
- versioned_docs/version-v3.0/framework-integration/angular.md
- versioned_docs/version-v3.1/framework-integration/angular.md
- versioned_docs/version-v3.2/framework-integration/angular.md
this commit updates the entries for
`includeSingleComponentAngularModules` as experimental, and states that its behaviors are subject to change
> docs(angular): mark includeSingleComponentAngularModules as experimental

- docs/output-targets/docs-json.md
- versioned_docs/version-v3.2/output-targets/docs-json.md
This updates the documentation for the `docs-json` output target, making the following changes:
- most of the prose is rewritten for clarity and readability (or subjectively what I find clearer)
- code blocks have filename titles added
- example components are fleshed out to more fully show the context
- a few 'caution' notes are added to explain potentially tricky behavior
- some more example JSON output is shown throughout
> update documentation for the `docs-json` output target

- docs/output-targets/docs-custom.md
- versioned_docs/version-v3.2/output-targets/docs-custom.md
This fills out the table describing the shape of the `JsonDocsComponent` type on the page for custom docs. I added links over to the updated JSON documentation page where appropriate.
> fill out table for docs-custom

- docs/documentation-generation/docs-custom.md
- docs/documentation-generation/docs-json.md
- docs/documentation-generation/docs-readme.md
- docs/documentation-generation/docs-stats.md
- docs/documentation-generation/docs-vscode.md
- versioned_docs/version-v3.2/documentation-generation/docs-custom.md
- versioned_docs/version-v3.2/documentation-generation/docs-json.md
- versioned_docs/version-v3.2/documentation-generation/docs-readme.md
- versioned_docs/version-v3.2/documentation-generation/docs-stats.md
- versioned_docs/version-v3.2/documentation-generation/docs-vscode.md
this commit updates the sidebar titles for the docs-* output targets, as
well as updating additional metadata for docusaurus for consistency
**EDIT**: @tanner-reits has given an initial sign off, I'll propagate this to v3.2 now, and if we need to change anything I'll just change it in both place
> docs(docs): update sidebar

- docs/testing/01-overview.md
- versioned_docs/version-v3.2/testing/01-overview.md
this commit updates the docs to add a double dash to the command used in vscode configs.
> chore(testing): add double dash to command

- .github/workflows/check-links.yml
- package.json
this pr bumps the version of node used in the project to v20. it also updates the setup node step in ci to ensure that the version of node used is pulled from the `volta` key in `package.json`
> chore(node): use node 20 for development

- docs/config/cli.md
- docs/testing/config.md
- versioned_docs/version-v3.3/config/cli.md
- versioned_docs/version-v3.3/testing/config.md
this commit backfills flag and configuration info for --devtools and browserDevtools, respectively
> docs(test): add devtools doc

- docs/config/extras.md
Removes the `__deprecated__shadowDomShim` from the `extras` docs. This was removed from #1129 since the option had not yet been removed from the Stencil compiler/runtime
> removes shadowDomShim from extras docs

- docs/config/01-overview.md
- docs/output-targets/01-overview.md
- docs/output-targets/custom-elements.md
- docs/output-targets/dist.md
- versioned_docs/version-v3.4/config/01-overview.md
- versioned_docs/version-v3.4/output-targets/01-overview.md
- versioned_docs/version-v3.4/output-targets/custom-elements.md
- versioned_docs/version-v3.4/output-targets/dist.md
Adds documentation for the multi-target field validation. This does _not_ need to be propagated to versioned docs since this behavior will only be available starting in v3.3
**NOTE:** this is pending the open PR in the Stencil repo and any potential changes that will be made there.
> docs(output-targets): enabling & configuring target validation

- docs/introduction/upgrading-to-stencil-four.md
this commit backfills the migration guide with ways users can/must update
their code to work with stencil v4.
---
the goal is to have this landed by Friday, which is the release of v4-rc.0
---
this commit has a sibling PR on the Stencil Repo - https://github.com/ionic-team/stencil/pull/4488
> docs(v4): backfill v4 migration guide

- versioned_docs/version-v3.4/testing/config.md
Snuck in in #1141 - anyways, quick and easy!
> docs(config): fix headful mode typo

- versioned_docs/version-v3.4/framework-integration/angular.md
this commit fixes an issue where the documentation in #1148 for the 3.4 docs was accidentally overwritten in #1141 (58235d447cd1c0bec502b47af9c9c5cf78a299cd). this was generated by checking out the head of `main` (58235d447cd1c0bec502b47af9c9c5cf78a299cd) and `git cherry-pick c288f3e979e09607b9e27c5a587712a53347ccc3`. Looking at the diff from #1141, that appears to be the only thing that was overwritten
> docs(angular): fixup app initializer 

- docs/config/01-overview.md
- docs/introduction/upgrading-to-stencil-four.md
- docs/output-targets/dist.md
this commit updates the upgrade guide for stencil v4 to include new default values for `transformAliasedImportPaths` and `transformAliasedImportPathsInCollection`.
STENCIL-829
Core PR: https://github.com/ionic-team/stencil/pull/4418
> docs(config): update updating guide for transformAliasedImportPaths

- vercel.json
In #1159 we consolidated our versions for v3.0..v3.4 down to a single united 'v3' version which will be the single maintained documentation for v3 going forward (we have a policy of only maintaining point-release specific documentation for the current major version number).
That change (#1159) involved setting up a Vercel redirect to take all requests for v3.x documentation and redirecting them to the same path under `/docs/`, so that, for instance, `/docs/v3.1/support-policy` redirects to `/docs/support-policy`. This commit amends that redirect so that instead that same url will redirect to `/docs/v3/support-policy`, since the main version under `/docs/` is now v4.
You can test that a url like `/docs/v3.1/support-policy` is redirected to `/docs/v3/support-policy` although note that until …
> [blocked] chore(docs): set up redirect from '3.x' versions to 'v3'

- docs/components/functional-components.md
- versioned_docs/version-v4.0/components/functional-components.md
Fixes minor grammar issue and improves readability of "Working with children" section of functional components page
> docs(functional-components): fix minor grammar issue

- docs/framework-integration/angular.md
- versioned_docs/version-v2/framework-integration/angular.md
- versioned_docs/version-v3/framework-integration/angular.md
- versioned_docs/version-v4.0/framework-integration/angular.md
The Framework team plans to move the `angular` directory to `packages/angular` in https://github.com/ionic-team/ionic-framework/pull/27719. This PR updates the links on the Stencil Site to point to the new location. Let me know if you'd rather I use permalinks.
Blocked on merging until https://github.com/ionic-team/ionic-framework/pull/27719 is merged.
> docs: update Ionic Angular links

- docs/framework-integration/vue.md
- versioned_docs/version-v2/framework-integration/vue.md
- versioned_docs/version-v3/framework-integration/vue.md
- versioned_docs/version-v4.0/framework-integration/vue.md
The documentation is confusing when you scroll further down and you dont actually have a /src/ folder anywhere, only /lib/ and the index.ts and plugin.ts file under it.
> docs(vue): update example vue library structure

- docs/guides/module-bundling.md
- versioned_docs/version-v4.0/guides/module-bundling.md
this commit removes the documentation around the `namedExports` field that is being deprecated in stencil v4. the field is no longer honored by the commonjs rollup plugin. we remove the documentation here to avoid any confusion surrounding its usability
STENCIL-867
https://github.com/ionic-team/stencil/pull/4532
> docs(bundling): remove commonjs#namedExports field

- docs/introduction/03-getting-started.md
- versioned_docs/version-v2/introduction/03-getting-started.md
- versioned_docs/version-v3/introduction/03-getting-started.md
- versioned_docs/version-v4.0/introduction/03-getting-started.md
this commit updates the documentation to note that a future version of the create-stencil cli will create a git repo locally for users
relates to: https://github.com/ionic-team/create-stencil/pull/240/
Note: I'll backport this to v2 once approved
> docs(getting-started): add git repo creation notice

- docs/components/events.md
- versioned_docs/version-v2/components/events.md
- versioned_docs/version-v3/components/events.md
- versioned_docs/version-v4.0/components/events.md
this commit adds a workaround/note about collisions between the native web `Event` type and stencil's decorator.
based on: https://discord.com/channels/520266681499779082/1131898715217612911/1131898715217612911
Note: I'll backport this all the way to v2 once approved
> docs(event): add note about colliding event types

- docs/framework-integration/react.md
- docs/framework-integration/vue.md
- versioned_docs/version-v2/framework-integration/react.md
- versioned_docs/version-v2/framework-integration/vue.md
- versioned_docs/version-v3/framework-integration/react.md
- versioned_docs/version-v3/framework-integration/vue.md
- versioned_docs/version-v4.0/framework-integration/react.md
- versioned_docs/version-v4.0/framework-integration/vue.md
Updates the documentation for the React and Vue output targets to include a FAQ entry for users encountering a "cannot read property of undefined (reading `isProxied`)".
Also updates some config diffs to make packages publishable.
> docs(wrappers): add `enableImportInjection` to FAQ

- docs/testing/config.md
- docs/testing/e2e-testing.md
- versioned_docs/version-v2/testing/config.md
- versioned_docs/version-v2/testing/e2e-testing.md
- versioned_docs/version-v3/testing/config.md
- versioned_docs/version-v3/testing/e2e-testing.md
- versioned_docs/version-v4.0/testing/config.md
- versioned_docs/version-v4.0/testing/e2e-testing.md
Updates testing documentation with a recipe for `setViewport` to emulate device displays within e2e tests.
> docs(testing): add recipe for `setViewport`

- docs/framework-integration/ember.md
- versioned_docs/version-v4.0/framework-integration/ember.md
Demo proving that `checked` and `ionChange` or the APIs for turning `ion-toggle` in to a _controlled_ component: [here (live demo)](https://limber.glimdown.com/edit?c=MQAgqgzglgdg5iAygFwKYwMZQDYliAUQFsAjVAJwChKB9AQRhpAEMYIB3CkZAe24AsoEEAG0IyZhgDWPAG4UAZth7sQARwCuqcVB4wAuiLUBGfSAXkeREAAMAAgBkeABx42AdNSOmAXCH7IyM4QPgD0oeKSMvLkSiruGFahmtrIumyhAOwAbDkALAAMAMwArKGopBQAtCVVxlXsUMj8VRVk5FUY2FBV4uhY2FWsACZVzVDko87M5MgAnp1WrjDoyBBVMDzIDTzkUrBw1JQAPACEVVUglPjjwqjDTbsA5MIAREQzUsMqMCBEPMNUK8ADRXTggDCsEDdeStAAeqAwGjQEIBqBAJDmLGGD3gIFeMKB3D4zXRcAAVsJEoCFP1UJQLgA%2Bag2VkU4SE65EVyzEAAbxAehAAF9zJZrE87G0KKF-g8FFAKE8ANxcnnIEAAYSWelWYqsIElcG6RCIMsS3N1MGQKrVuw1AuQ5Ci9xF%2BoldmNUFNMqdUQOtsoXWYEGEABEKnxUHC0DBhsJtZaVtb%2BZQQCBjmhudhmGhmen00IAPIwPx8vm3dzFmDC4VpgvHEjkfMN9JjHhwY3ojD8RFSe4AXle5cr1drr35fKFr3Smv4rDgRMr …
> [Ember] Update example for Ionic-specific APIs

- CONTRIBUTING.md
- package.json
I think we need the `--frail` option so it will `exit(1)` when there's a warning and thereby fail the build
The first commit makes it so the build fails, and the second fixes the issue.
> chore(ci): make markdown link checker fail correctly

- docs/config/extras.md
A small documentation PR just adding a bit of explanation of what this field is for.
> docs(config): add docs for new `experimentalSlotFixes` config value

- docs/components/component.md
- versioned_docs/version-v2/components/component.md
- versioned_docs/version-v3/components/component.md
- versioned_docs/version-v4.0/components/component.md
- versioned_docs/version-v4.1/components/component.md
this commit fixes some garbled text that didn't make any real sense when read back.
partially addresses https://github.com/ionic-team/stencil-site/issues/1214
longer term, I'd like us to properly document modes as a part of the component API and link that back to these sections
> docs(component): fix wording for styles

- docs/config/extras.md
- versioned_docs/version-v4.2/config/extras.md
this commit adds https://github.com/ionic-team/stencil/issues/2641 to the list of issues fixed when enabling `experimentalSlotFixes`
> docs(config): update experimentalSlotFixes bug fix list

- docs/components/reactive-data.md
Adds a section to the `@Watch()` decorator docs for use with native HTML attributes. Also does a bit of re-wording to a few sentences.
> docs(reactive-data): add section for watching native attributes

- docs/framework-integration/angular.md
This just updates the FAQ for configuring the output target to use the `dist-custom-elements` output. This was a small oversight when the API changed in the 0.8.2 release.
> docs(angular): update section for configuring to use custom elements

- docs/reference/support-policy.md
This adds an entry to the table where we note the versions of Stencil where we upgrade TypeScript to include information about the forthcoming upgrade to TypeScript 5.2.2 in Stencil 4.4.0.
Relevant to https://github.com/ionic-team/stencil/pull/4852
> docs(ts): add TypeScript 5.2.2 <-> Stencil 4.4.0 note

- docs/components/templating-and-jsx.md
- versioned_docs/version-v2/components/templating-and-jsx.md
- versioned_docs/version-v3/components/templating-and-jsx.md
- versioned_docs/version-v4.0/components/templating-and-jsx.md
- versioned_docs/version-v4.1/components/templating-and-jsx.md
- versioned_docs/version-v4.2/components/templating-and-jsx.md
- versioned_docs/version-v4.3/components/templating-and-jsx.md
- versioned_docs/version-v4.4/components/templating-and-jsx.md
Adds a note for a potential workaround for slot issues outside the Shadow DOM.
> docs(slots): add note for workaround with slots outside shadow DOM

- cspell-wordlist.txt
- docs/components/component.md
- docs/components/form-associated.md
This adds documentation of:
- building FACE generally, including how to use the `AttachInternals` decorator added in https://github.com/ionic-team/stencil/pull/4784
- the `formAssociated` option added to the argument passed to the `@Component` decorator, also added in https://github.com/ionic-team/stencil/pull/4784
> docs for form-associated custom elements in Stencil

- docs/reference/support-policy.md
add wording to next/ docs (slated for v4.7) to state we support jest 28/29 starting with v4.7.0. coalesce the support table for v24-26 to minimize the horizontal space the table was taking up
> docs(suppport): add jest 28-29 to next/ docs

- docs/components/styling.md
- docs/config/cli.md
- docs/introduction/03-getting-started.md
- versioned_docs/version-v4.0/components/styling.md
- versioned_docs/version-v4.0/config/cli.md
- versioned_docs/version-v4.0/introduction/03-getting-started.md
- versioned_docs/version-v4.1/components/styling.md
- versioned_docs/version-v4.1/config/cli.md
- versioned_docs/version-v4.1/introduction/03-getting-started.md
- versioned_docs/version-v4.2/components/styling.md
- versioned_docs/version-v4.2/config/cli.md
- versioned_docs/version-v4.2/introduction/03-getting-started.md
- versioned_docs/version-v4.3/components/styling.md
- versioned_docs/version-v4.3/config/cli.md
- versioned_docs/version-v4.3/introduction/03-getting-started.md
- versioned_docs/version-v4.4/components/styling.md
- versioned_docs/version-v4.4/config/cli.md
- versioned_docs/version-v4.4/introduction/03-getting-started.md
- versioned_docs/version-v4.5/components/styling.md
- versioned_docs/version-v4.5/config/cli.md
- versioned_docs/version-v4.5/introduction/03-getting-started.md
- versioned_docs/version-v4.6/components/styling.md
- versioned_docs/version-v4.6/config/cli.md
- versioned_docs/version-v4.6/introduction/03-getting-started.md
- versioned_docs/version-v4.7/components/styling.md
- versioned_docs/version-v4.7/config/cli.md
- versioned_docs/version-v4.7/introduction/03-getting-started.md
add the documentation for the generate task to the cli documentation.
this commit also removes it from the getting started section of the
documentation for a more cohesive feel (and to reduce repetition).
no redirects have been added, as anchor tag redirects are not supported
at this time
Depends on: #1264 landing first
I'll propagate this back to all v4 entries once approved and the parent PR lands
> docs(cli): add generate task to cli documentation 

- docs/documentation-generation/docs-readme.md
- versioned_docs/version-v4.0/documentation-generation/docs-readme.md
- versioned_docs/version-v4.1/documentation-generation/docs-readme.md
- versioned_docs/version-v4.2/documentation-generation/docs-readme.md
- versioned_docs/version-v4.3/documentation-generation/docs-readme.md
- versioned_docs/version-v4.4/documentation-generation/docs-readme.md
- versioned_docs/version-v4.5/documentation-generation/docs-readme.md
- versioned_docs/version-v4.6/documentation-generation/docs-readme.md
- versioned_docs/version-v4.7/documentation-generation/docs-readme.md
clarify when/how `docs-readme` is run.
arguably, this is the minimal amount of work needed to close the ticket below.
I've stubbed STENCIL-998 to work on our doc-generation sub section as a whole
closes: https://github.com/ionic-team/stencil/issues/2483
requires: https://github.com/ionic-team/stencil-site/pull/1264 to land first, which has a new link to the `docs` task
> docs(readme): clarify when readme is generated

- docs/config/cli.md
- versioned_docs/version-v4.0/config/cli.md
- versioned_docs/version-v4.1/config/cli.md
- versioned_docs/version-v4.2/config/cli.md
- versioned_docs/version-v4.3/config/cli.md
- versioned_docs/version-v4.4/config/cli.md
- versioned_docs/version-v4.5/config/cli.md
- versioned_docs/version-v4.6/config/cli.md
- versioned_docs/version-v4.7/config/cli.md
add explicit sections for the help and version tasks, rather than
grouping them under the vague header 'stencil'
Depends on: https://github.com/ionic-team/stencil-site/pull/1265 landing first
I'll propagate this back to all v4 entries once approved and the parent PR lands
>  docs(cli): add help and version tasks

- docs/components/events.md
Updates the verbiage around the recommendation for dealing with type conflicts in the `Event` decorator import with the addition of support for import aliasing.
Also peeked through the docs for some of our other decorators and didn't see anything needing updating there.
**Note:** This does **not** need to be propagated to other versions as this will only be available starting in v4.9
> docs(events): update type conflict recommendation

- docs/reference/support-policy.md
- versioned_docs/version-v3/reference/support-policy.md
- versioned_docs/version-v4.0/reference/support-policy.md
- versioned_docs/version-v4.1/reference/support-policy.md
- versioned_docs/version-v4.2/reference/support-policy.md
- versioned_docs/version-v4.3/reference/support-policy.md
- versioned_docs/version-v4.4/reference/support-policy.md
- versioned_docs/version-v4.5/reference/support-policy.md
- versioned_docs/version-v4.6/reference/support-policy.md
- versioned_docs/version-v4.7/reference/support-policy.md
- versioned_docs/version-v4.8/reference/support-policy.md
- versioned_docs/version-v4.9/reference/support-policy.md
**Note: This should not be merged before 2023.12.26**
**Note:** ~If we release v4.9 on Monday, 2023.12.18, I'll need to update this PR~ Done
update the support policy table to denote that stencil v3 has moved to extended support status.
> chore(support): move stencil v3 to extended support

- docs/testing/01-overview.md
- versioned_docs/version-v2/testing/01-overview.md
- versioned_docs/version-v3/testing/01-overview.md
- versioned_docs/version-v4.0/testing/01-overview.md
- versioned_docs/version-v4.1/testing/01-overview.md
- versioned_docs/version-v4.2/testing/01-overview.md
- versioned_docs/version-v4.3/testing/01-overview.md
- versioned_docs/version-v4.4/testing/01-overview.md
- versioned_docs/version-v4.5/testing/01-overview.md
- versioned_docs/version-v4.6/testing/01-overview.md
- versioned_docs/version-v4.7/testing/01-overview.md
- versioned_docs/version-v4.8/testing/01-overview.md
- versioned_docs/version-v4.9/testing/01-overview.md
Based on a question we've received in https://github.com/ionic-team/stencil/discussions/5225#discussioncomment-8084146 I think it is worth to document this.
> docs(testing): document how to pass in Jest CLI arguments

- docs/reference/support-policy.md
- versioned_docs/version-v4.4/reference/support-policy.md
- versioned_docs/version-v4.5/reference/support-policy.md
- versioned_docs/version-v4.6/reference/support-policy.md
- versioned_docs/version-v4.7/reference/support-policy.md
- versioned_docs/version-v4.8/reference/support-policy.md
- versioned_docs/version-v4.9/reference/support-policy.md
This is assuming that the [PR with the update](https://github.com/ionic-team/stencil/pull/5248) is part of a minor Stencil release. I will move this PR out of draft once this is verified and the docs update is ready.
> docs(support): add support note for TypeScript 5.3 in Stencil v4.10 and higher

- docs/config/extras.md
- versioned_docs/version-v4.10/config/extras.md
- versioned_docs/version-v4.2/config/extras.md
- versioned_docs/version-v4.3/config/extras.md
- versioned_docs/version-v4.4/config/extras.md
- versioned_docs/version-v4.5/config/extras.md
- versioned_docs/version-v4.6/config/extras.md
- versioned_docs/version-v4.7/config/extras.md
- versioned_docs/version-v4.8/config/extras.md
- versioned_docs/version-v4.9/config/extras.md
Adds links to issues resolved by the `experimentalSlotFixes` flag in the corresponding versions
> docs(extras): link slot fix issues for versions

- docs/components/templating-and-jsx.md
Add some documentation to our page on JSX which explains the changes made in https://github.com/ionic-team/stencil/pull/5143
> docs(jsx): add explanation of automatic key insertion

- docs/config/cli.md
- docs/documentation-generation/docs-readme.md
- versioned_docs/version-v3/config/cli.md
- versioned_docs/version-v3/documentation-generation/docs-readme.md
- versioned_docs/version-v4.0/config/cli.md
- versioned_docs/version-v4.0/documentation-generation/docs-readme.md
- versioned_docs/version-v4.1/config/cli.md
- versioned_docs/version-v4.1/documentation-generation/docs-readme.md
- versioned_docs/version-v4.10/config/cli.md
- versioned_docs/version-v4.10/documentation-generation/docs-readme.md
- versioned_docs/version-v4.11/config/cli.md
- versioned_docs/version-v4.11/documentation-generation/docs-readme.md
- versioned_docs/version-v4.12/config/cli.md
- versioned_docs/version-v4.12/documentation-generation/docs-readme.md
- versioned_docs/version-v4.2/config/cli.md
- versioned_docs/version-v4.2/documentation-generation/docs-readme.md
- versioned_docs/version-v4.3/config/cli.md
- versioned_docs/version-v4.3/documentation-generation/docs-readme.md
- versioned_docs/version-v4.4/config/cli.md
- versioned_docs/version-v4.4/documentation-generation/docs-readme.md
- versioned_docs/version-v4.5/config/cli.md
- versioned_docs/version-v4.5/documentation-generation/docs-readme.md
- versioned_docs/version-v4.6/config/cli.md
- versioned_docs/version-v4.6/documentation-generation/docs-readme.md
- versioned_docs/version-v4.7/config/cli.md
- versioned_docs/version-v4.7/documentation-generation/docs-readme.md
- versioned_docs/version-v4.8/config/cli.md
- versioned_docs/version-v4.8/documentation-generation/docs-readme.md
- versioned_docs/version-v4.9/config/cli.md
- versioned_docs/version-v4.9/documentation-generation/docs-readme.md
add additional documentation concerning the behavior of the `docs-readme` output target. this commit is close to entire rewrite of the documentation - it looks to fill in all details concerning the output target regarding its behavior
> docs(docs-readme): fill out docs-readme output target

- docs/config/extras.md
- versioned_docs/version-v4.12/config/extras.md
This adds https://github.com/ionic-team/stencil/issues/2982 to the list of fixes from `experimentalSlotFixes`
> docs(extras): add dynamic slot name change fix to slot fix list

- docs/config/01-overview.md
- versioned_docs/version-v2/config/01-overview.md
- versioned_docs/version-v3/config/01-overview.md
- versioned_docs/version-v4.0/config/01-overview.md
- versioned_docs/version-v4.1/config/01-overview.md
- versioned_docs/version-v4.10/config/01-overview.md
- versioned_docs/version-v4.11/config/01-overview.md
- versioned_docs/version-v4.12/config/01-overview.md
- versioned_docs/version-v4.2/config/01-overview.md
- versioned_docs/version-v4.3/config/01-overview.md
- versioned_docs/version-v4.4/config/01-overview.md
- versioned_docs/version-v4.5/config/01-overview.md
- versioned_docs/version-v4.6/config/01-overview.md
- versioned_docs/version-v4.7/config/01-overview.md
- versioned_docs/version-v4.8/config/01-overview.md
- versioned_docs/version-v4.9/config/01-overview.md
This adds documentation for the `hydratedFlag` config option, which controls how Stencil marks hydration on components.
fixes #882
STENCIL-1045
> docs(config): add documentation for `hydratedFlag`

- docs/config/cli.md
- versioned_docs/version-v4.1/config/cli.md
- versioned_docs/version-v4.10/config/cli.md
- versioned_docs/version-v4.11/config/cli.md
- versioned_docs/version-v4.12/config/cli.md
- versioned_docs/version-v4.2/config/cli.md
- versioned_docs/version-v4.3/config/cli.md
- versioned_docs/version-v4.4/config/cli.md
- versioned_docs/version-v4.5/config/cli.md
- versioned_docs/version-v4.6/config/cli.md
- versioned_docs/version-v4.7/config/cli.md
- versioned_docs/version-v4.8/config/cli.md
- versioned_docs/version-v4.9/config/cli.md
clarify when the `--no-build` flag can be used when running `npx stencil test`. this was motivated by a question in discord regarding `--no-build` and `--spec` being used (or if they should be used simultaneously) - https://discord.com/channels/520266681499779082/933029266562613309/1212752679579947008.
Note: I'll propagate this to other directories after it's been approved
> chore(cli): clarify --no-build-flag

- docs/config/extras.md
this pr accompanies https://github.com/ionic-team/stencil/pull/5365/, which is the fix for https://github.com/ionic-team/stencil/issue/5335
> docs(extras): add conditional slot rendering to experimentalSlotFixes

- versioned_docs/version-v3/output-targets/dist.md
- versioned_docs/version-v4.0/output-targets/dist.md
- versioned_docs/version-v4.1/output-targets/dist.md
- versioned_docs/version-v4.10/output-targets/dist.md
- versioned_docs/version-v4.11/output-targets/dist.md
- versioned_docs/version-v4.12/output-targets/dist.md
- versioned_docs/version-v4.13.0/output-targets/dist.md
- versioned_docs/version-v4.2/output-targets/dist.md
- versioned_docs/version-v4.3/output-targets/dist.md
- versioned_docs/version-v4.4/output-targets/dist.md
- versioned_docs/version-v4.5/output-targets/dist.md
- versioned_docs/version-v4.6/output-targets/dist.md
- versioned_docs/version-v4.7/output-targets/dist.md
- versioned_docs/version-v4.8/output-targets/dist.md
- versioned_docs/version-v4.9/output-targets/dist.md
we're a little misleading here with respect to how `dist` works. adding a new sentence to clarify this better.
Impetus: https://discord.com/channels/520266681499779082/1143895925325058121/1219625948647919659
> docs(dist): clarify `dist` output target

- docs/reference/support-policy.md
- versioned_docs/version-v4.13.0/reference/support-policy.md
update the typescript support table to account for typescript v5.4.3.
the thinking here even though this is a patch version of TS, it reverts a handful of PRs that made it into a release, whose behavior folks could be relying on. as a result, I'd rather be safe than sorry here.
update the v4.13.0 table to specify v5.4.2 instead of v5.4.0, as the typescript team uses the ".0" patch for beta releases and ".1" patch for RC at the moment.
For: https://github.com/ionic-team/stencil/pull/5588
> docs(support): update typescript support for 5.4.3

- docs/testing/stencil-testrunner/05-e2e-testing.md
__Background:__
I've discovered a limitation with Stencils deep locator and put up [a PR](https://github.com/ionic-team/stencil-site/pull/1373) to let users know about this limitation. Now, after working on https://github.com/ionic-team/stencil/pull/5481 this limitation was fixed and we can update the docs again.
__Summary:__
This patch documents that user can use multiple deep selectors in their queries.
> chore(test): update piercing docs

- docs/documentation-generation/docs-readme.md
- versioned_docs/version-v3/documentation-generation/docs-readme.md
- versioned_docs/version-v4.0/documentation-generation/docs-readme.md
- versioned_docs/version-v4.1/documentation-generation/docs-readme.md
- versioned_docs/version-v4.10/documentation-generation/docs-readme.md
- versioned_docs/version-v4.11/documentation-generation/docs-readme.md
- versioned_docs/version-v4.12/documentation-generation/docs-readme.md
- versioned_docs/version-v4.13.0/documentation-generation/docs-readme.md
- versioned_docs/version-v4.2/documentation-generation/docs-readme.md
- versioned_docs/version-v4.3/documentation-generation/docs-readme.md
- versioned_docs/version-v4.4/documentation-generation/docs-readme.md
- versioned_docs/version-v4.5/documentation-generation/docs-readme.md
- versioned_docs/version-v4.6/documentation-generation/docs-readme.md
- versioned_docs/version-v4.7/documentation-generation/docs-readme.md
- versioned_docs/version-v4.8/documentation-generation/docs-readme.md
- versioned_docs/version-v4.9/documentation-generation/docs-readme.md
add a section on the behavior of the `@internal` jsdoc tag
ths impetus for this is an internal slack convo with Liam in the ask-stencil channel
I'll backport it once it's been approved
> docs(ot-readme): add internal jsdoc documentation

- docs/core/compiler-api.md
- versioned_docs/version-v4.0/core/compiler-api.md
- versioned_docs/version-v4.1/core/compiler-api.md
- versioned_docs/version-v4.10/core/compiler-api.md
- versioned_docs/version-v4.11/core/compiler-api.md
- versioned_docs/version-v4.12/core/compiler-api.md
- versioned_docs/version-v4.13.0/core/compiler-api.md
- versioned_docs/version-v4.14/core/compiler-api.md
- versioned_docs/version-v4.2/core/compiler-api.md
- versioned_docs/version-v4.3/core/compiler-api.md
- versioned_docs/version-v4.4/core/compiler-api.md
- versioned_docs/version-v4.5/core/compiler-api.md
- versioned_docs/version-v4.6/core/compiler-api.md
- versioned_docs/version-v4.7/core/compiler-api.md
- versioned_docs/version-v4.8/core/compiler-api.md
- versioned_docs/version-v4.9/core/compiler-api.md
It turns out this is not supported anymore since v3.3.0 of Stencil and the introduction of TypeScript v5. This patch removes these artifacts from the docs, except v3 and v2.
> docs(compiler): remove docs on loading the Stencil compiler in a Web Worker or browser

- docs/testing/playwright/01-overview.md
- versioned_docs/version-v4.13.0/testing/playwright/01-overview.md
- versioned_docs/version-v4.14/testing/playwright/01-overview.md
- versioned_docs/version-v4.15/testing/playwright/01-overview.md
Adds a section to the Playwright overview for users coming from an established e2e testing setup using the Stencil Test Runner. This covers ways in which users can test out the Playwright adapter without fully migrating, or for updating file match patterns while a project is migrated to use Playwright over time.
Changes also backfilled to v4.13, v4.14, & v4.15 docs.
> docs(playwright): add section for migrating to/testing playwright

- docs/core/compiler-api.md
- versioned_docs/version-v4.0/core/compiler-api.md
- versioned_docs/version-v4.1/core/compiler-api.md
- versioned_docs/version-v4.10/core/compiler-api.md
- versioned_docs/version-v4.11/core/compiler-api.md
- versioned_docs/version-v4.12/core/compiler-api.md
- versioned_docs/version-v4.13.0/core/compiler-api.md
- versioned_docs/version-v4.14/core/compiler-api.md
- versioned_docs/version-v4.15/core/compiler-api.md
- versioned_docs/version-v4.2/core/compiler-api.md
- versioned_docs/version-v4.3/core/compiler-api.md
- versioned_docs/version-v4.4/core/compiler-api.md
- versioned_docs/version-v4.5/core/compiler-api.md
- versioned_docs/version-v4.6/core/compiler-api.md
- versioned_docs/version-v4.7/core/compiler-api.md
- versioned_docs/version-v4.8/core/compiler-api.md
- versioned_docs/version-v4.9/core/compiler-api.md
> docs(compiler): remove references to using the compiler in a browser

- docs/reference/support-policy.md
add typescript v5.4.5 to the support table for the upcoming release of stencil v4.16.0
this commit compliments https://github.com/ionic-team/stencil/pull/5663
> docs(typescript): add ts v5.4.5 to support table

- docs/testing/playwright/01-overview.md
- docs/testing/playwright/02-e2e-testing.md
- docs/testing/playwright/03-api.md
- versioned_docs/version-v4.13.0/testing/playwright/01-overview.md
- versioned_docs/version-v4.13.0/testing/playwright/02-e2e-testing.md
- versioned_docs/version-v4.13.0/testing/playwright/03-api.md
- versioned_docs/version-v4.14/testing/playwright/01-overview.md
- versioned_docs/version-v4.14/testing/playwright/02-e2e-testing.md
- versioned_docs/version-v4.14/testing/playwright/03-api.md
- versioned_docs/version-v4.15/testing/playwright/01-overview.md
- versioned_docs/version-v4.15/testing/playwright/02-e2e-testing.md
- versioned_docs/version-v4.15/testing/playwright/03-api.md
- versioned_docs/version-v4.16/testing/playwright/01-overview.md
- versioned_docs/version-v4.16/testing/playwright/02-e2e-testing.md
- versioned_docs/version-v4.16/testing/playwright/03-api.md
- versioned_docs/version-v4.17/testing/playwright/01-overview.md
- versioned_docs/version-v4.17/testing/playwright/02-e2e-testing.md
- versioned_docs/version-v4.17/testing/playwright/03-api.md
Updates the Playwright adapter config creation helper from `createStencilPlaywrightConfig` to `createConfig`.
Documentation changes for associated change in the Playwright adapter: https://github.com/ionic-team/stencil-playwright/pull/37
> fix(docs): update playwright config helper function name

- docs/testing/playwright/03-api.md
- versioned_docs/version-v4.13.0/testing/playwright/03-api.md
- versioned_docs/version-v4.14/testing/playwright/03-api.md
- versioned_docs/version-v4.15/testing/playwright/03-api.md
- versioned_docs/version-v4.16/testing/playwright/03-api.md
- versioned_docs/version-v4.17/testing/playwright/03-api.md
Updates the Playwright adapter `createConfig` signature and description. This talks about the new "deep merge" approach for overriding config values and gives a small example.
Associated adapter change: https://github.com/ionic-team/stencil-playwright/pull/38
> feat(docs): update playwright config helper signature & description

- docs/testing/playwright/01-overview.md
- versioned_docs/version-v4.13.0/testing/playwright/01-overview.md
- versioned_docs/version-v4.14/testing/playwright/01-overview.md
- versioned_docs/version-v4.15/testing/playwright/01-overview.md
- versioned_docs/version-v4.16/testing/playwright/01-overview.md
- versioned_docs/version-v4.17/testing/playwright/01-overview.md
Adds a note admonition to the Playwright adapter docs for the naming limitation around the Stencil config. This note already exists in the adapter readme, so just porting it over here as well.
> docs(playwright): add note for Stencil config naming limitation

- docs/framework-integration/angular.md
- versioned_docs/version-v4.0/framework-integration/angular.md
- versioned_docs/version-v4.1/framework-integration/angular.md
- versioned_docs/version-v4.10/framework-integration/angular.md
- versioned_docs/version-v4.11/framework-integration/angular.md
- versioned_docs/version-v4.12/framework-integration/angular.md
- versioned_docs/version-v4.13.0/framework-integration/angular.md
- versioned_docs/version-v4.14/framework-integration/angular.md
- versioned_docs/version-v4.15/framework-integration/angular.md
- versioned_docs/version-v4.16/framework-integration/angular.md
- versioned_docs/version-v4.17/framework-integration/angular.md
- versioned_docs/version-v4.2/framework-integration/angular.md
- versioned_docs/version-v4.3/framework-integration/angular.md
- versioned_docs/version-v4.4/framework-integration/angular.md
- versioned_docs/version-v4.5/framework-integration/angular.md
- versioned_docs/version-v4.6/framework-integration/angular.md
- versioned_docs/version-v4.7/framework-integration/angular.md
- versioned_docs/version-v4.8/framework-integration/angular.md
- versioned_docs/version-v4.9/framework-integration/angular.md
This adds a note about the build issue documented in https://github.com/ionic-team/stencil/issues/5427 just so that users of the Angular OT are forewarned.
STENCIL-1193
once this is approved I'll port it to other versions
> docs(angular): add a note about possible build warning

- docs/documentation-generation/docs-json.md
add an example of the output for modes associated with a stylesheet.
associated with https://github.com/ionic-team/stencil/pull/5718
STENCIL-1269
> docs(json): add mode to docs-json docs

- docs/testing/stencil-testrunner/03-unit-testing.md
This requires https://github.com/ionic-team/stencil/pull/5722 to land first as it enables usage of functional components in unit tests.
> docs(testing): better document how to test functional components

- docs/config/01-overview.md
This adds docs around the `rollupConfig` overwrite config.
> docs(config): document 'rollupConfig'

- cspell-wordlist.txt
- docs/guides/hydrate-app.md
Documentation on changes made in https://github.com/ionic-team/stencil/pull/5792
> docs(declarative-shadow-dom): update docs on component hydration

- docs/config/01-overview.md
Adds documentation for the `generateExportMaps` config option introduced by https://github.com/ionic-team/stencil/pull/5809
> docs(config): document `generateExportMaps` config option & function

- docs/config/01-overview.md
Adds documentation for the `watchIgnoredRegex` Stencil config option.
I do not intend to backfill these changes to previous versions since v4.20 will be the first version to support tsconfig watchOptions
> docs(config): add watchIgnoredRegex

- versioned_docs/version-v4.0/output-targets/dist.md
- versioned_docs/version-v4.1/output-targets/dist.md
- versioned_docs/version-v4.10/output-targets/dist.md
- versioned_docs/version-v4.11/output-targets/dist.md
- versioned_docs/version-v4.12/output-targets/dist.md
- versioned_docs/version-v4.2/output-targets/dist.md
- versioned_docs/version-v4.3/output-targets/dist.md
- versioned_docs/version-v4.4/output-targets/dist.md
- versioned_docs/version-v4.5/output-targets/dist.md
- versioned_docs/version-v4.6/output-targets/dist.md
- versioned_docs/version-v4.7/output-targets/dist.md
- versioned_docs/version-v4.8/output-targets/dist.md
- versioned_docs/version-v4.9/output-targets/dist.md
We use this import example in one of the comments in earlier Stencil versions, this patch improves that comment with a more concrete example on how to import.
This takes the proposal from #1067 and applies it on all documentation versions.
> fix(docs): minor improvement to import comment

- docs/components/properties.md
- versioned_docs/version-v2/components/properties.md
- versioned_docs/version-v3/components/properties.md
- versioned_docs/version-v4.0/components/properties.md
- versioned_docs/version-v4.1/components/properties.md
- versioned_docs/version-v4.10/components/properties.md
- versioned_docs/version-v4.11/components/properties.md
- versioned_docs/version-v4.12/components/properties.md
- versioned_docs/version-v4.13.0/components/properties.md
- versioned_docs/version-v4.14/components/properties.md
- versioned_docs/version-v4.15/components/properties.md
- versioned_docs/version-v4.16/components/properties.md
- versioned_docs/version-v4.17/components/properties.md
- versioned_docs/version-v4.18/components/properties.md
- versioned_docs/version-v4.19/components/properties.md
- versioned_docs/version-v4.2/components/properties.md
- versioned_docs/version-v4.20/components/properties.md
- versioned_docs/version-v4.3/components/properties.md
- versioned_docs/version-v4.4/components/properties.md
- versioned_docs/version-v4.5/components/properties.md
- versioned_docs/version-v4.6/components/properties.md
- versioned_docs/version-v4.7/components/properties.md
- versioned_docs/version-v4.8/components/properties.md
- versioned_docs/version-v4.9/components/properties.md
Some of the components had different closing tags to the opening tags specified by the component creation.
Linked to issue #1471
> doc(components/properties.md): update erroneous closing tags on components

- docs/guides/hydrate-app.md
- versioned_docs/version-v4.20/guides/hydrate-app.md
Adding updates to the docs according to our recent releases: `serializeShadowRoot` is `true` by default starting v4.19. Also improving docs around `hydrateDocument` making the example a bit more concrete.
> docs(hydrate): better docs around hydrateDocument and renderToString

- docs/framework-integration/react.md
Updates the documentation for the React framework integration page for the changes from https://github.com/ionic-team/stencil-ds-output-targets/pull/428.
- Updates minimum React 17 requirement
- Removes explicit typescript version, this is dependent on the version of Stencil
- Updates to minimum Stencil v4.2.0 requirement
- Updates the description and benefits list of using the framework wrappers
- Adds file titles for code snippets 
- Removes `dist` FAQ and adds a new FAQ explaining the output target only supports `dist-custom-elements`
- Updates API reference with the new public API 
- Adds installation instruction for runtime dependency for framework wrappers
Quick preview: https://stencil-docs-git-sp-react-output-target-ionic1.vercel.app/docs/next/react
> docs(react): instructions for next version of react-output-target

- package-lock.json
- package.json
This PR:
- bumps ionic preset to latest
- updates npm2yarn plugin to latest 3.5
- removes docusaurus plugins that have been abstracted to preset
> chore: support docusaurus 3.5

- docs/framework-integration/react.md
- versioned_docs/version-v4.0/framework-integration/react.md
- versioned_docs/version-v4.1/framework-integration/react.md
- versioned_docs/version-v4.10/framework-integration/react.md
- versioned_docs/version-v4.11/framework-integration/react.md
- versioned_docs/version-v4.12/framework-integration/react.md
- versioned_docs/version-v4.13.0/framework-integration/react.md
- versioned_docs/version-v4.14/framework-integration/react.md
- versioned_docs/version-v4.15/framework-integration/react.md
- versioned_docs/version-v4.16/framework-integration/react.md
- versioned_docs/version-v4.17/framework-integration/react.md
- versioned_docs/version-v4.18/framework-integration/react.md
- versioned_docs/version-v4.19/framework-integration/react.md
- versioned_docs/version-v4.2/framework-integration/react.md
- versioned_docs/version-v4.20/framework-integration/react.md
- versioned_docs/version-v4.21/framework-integration/react.md
- versioned_docs/version-v4.3/framework-integration/react.md
- versioned_docs/version-v4.4/framework-integration/react.md
- versioned_docs/version-v4.5/framework-integration/react.md
- versioned_docs/version-v4.6/framework-integration/react.md
- versioned_docs/version-v4.7/framework-integration/react.md
- versioned_docs/version-v4.8/framework-integration/react.md
- versioned_docs/version-v4.9/framework-integration/react.md
With the React output target being able to generate optimized components for Next.js server side rendering, this PR adds necessary documentation for this new feature.
> docs(react): document new react output target flag for Next.js server side rendering

- docs/components/api.md
Closes https://github.com/ionic-team/stencil-site/issues/1465.
> Fix `getElement` type in doc

- docs/framework-integration/react.md
Companion PR for https://github.com/ionic-team/stencil-ds-output-targets/pull/540
I also removed the note saying that SSR support only works for Next.js App Router which is not true. The type of router shouldn't matter as long as the user uses Next.js v13 and above.
> react: add docs for excludeServerSideRenderingFor option

- docs/output-targets/dist.md
Docs regarding 'Distribution Options' in Stencil were (I believe) wrongly removed.
1) they're useful
2) they're mentioned in remaining text - "loading the components directly through a script tag as mentioned below"
> undo dist.md 'Distribution Options' docs

- docs/framework-integration/react.md
- versioned_docs/version-v4.23/framework-integration/react.md
In React we've discovered limitations around rendering nested components, see https://github.com/ionic-team/stencil-ds-output-targets/pull/573. As we suppress the error message, let's document this limitation better to make people aware.
> docs(react): document ssr limitations around nested components

- docs/reference/versioning.md
- versioned_docs/version-v2/reference/versioning.md
- versioned_docs/version-v3/reference/versioning.md
- versioned_docs/version-v4.0/reference/versioning.md
- versioned_docs/version-v4.1/reference/versioning.md
- versioned_docs/version-v4.10/reference/versioning.md
- versioned_docs/version-v4.11/reference/versioning.md
- versioned_docs/version-v4.12/reference/versioning.md
- versioned_docs/version-v4.13.0/reference/versioning.md
- versioned_docs/version-v4.14/reference/versioning.md
- versioned_docs/version-v4.15/reference/versioning.md
- versioned_docs/version-v4.16/reference/versioning.md
- versioned_docs/version-v4.17/reference/versioning.md
- versioned_docs/version-v4.18/reference/versioning.md
- versioned_docs/version-v4.19/reference/versioning.md
- versioned_docs/version-v4.2/reference/versioning.md
- versioned_docs/version-v4.20/reference/versioning.md
- versioned_docs/version-v4.21/reference/versioning.md
- versioned_docs/version-v4.22/reference/versioning.md
- versioned_docs/version-v4.23/reference/versioning.md
- versioned_docs/version-v4.3/reference/versioning.md
- versioned_docs/version-v4.4/reference/versioning.md
- versioned_docs/version-v4.5/reference/versioning.md
- versioned_docs/version-v4.6/reference/versioning.md
- versioned_docs/version-v4.7/reference/versioning.md
- versioned_docs/version-v4.8/reference/versioning.md
- versioned_docs/version-v4.9/reference/versioning.md
We no longer can guarantee major releases every 6 month, hence removing this statement from our versioning docs.
fixes #1503
> fix(versioning): remove timeline for major releases

- docs/guides/server-side-rendering.md
- docs/testing/04-jest.md
- versioned_docs/version-v4.33/guides/server-side-rendering.md
- versioned_docs/version-v4.33/testing/04-jest.md
- versioned_docs/version-v4.34/guides/server-side-rendering.md
- versioned_docs/version-v4.34/testing/04-jest.md
- versioned_docs/version-v4.35/guides/server-side-rendering.md
- versioned_docs/version-v4.35/testing/04-jest.md
With https://github.com/stenciljs/output-targets/pull/683 providing improvements to the runtime approach we should update our docs around this.
> docs(ssr): add more clarity on the two approaches in Next.js
