stenciljs/site

docs-md/basics/components.md
www/docs-content/basics/components.html

It requires () to operate correctly.

correct @Element usage

---

docs-md/start/index.md

`git clone git@github.com:ionic-team/stencil-starter my-app` gives for me the following error:
```
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
but `git clone https://github.com/ionic-team/stencil-starter.git my-app` works flawlessly.
p.s. great project 🔥

Fix git clone command

---

docs-md/basics/my-first-component.md
www/docs-content/basics/components.html
www/docs-content/basics/my-first-component.html

Fixing a small grammar issue in the docs with subject/verb agreement. 
Reference: 
https://webapps.towson.edu/ows/modulesvagr.htm

Fixing verb agreement in the docs look like -> looks like

---

readme.md

- Add link to the official website
- Improve clarity of the text

docs(README.md) add link to the official website

---

docs-md/basics/templating.md

- Fix syntax error in the documentation.

docs(templating.md) fix syntax error

---

docs-md/basics/my-first-component.md

Just going through the tutorial, found a simple typo

assuming users shouldn't actually worry :)

---

src/components/resources-page/resources-page.tsx

Added new article (Component interaction, Component communication)

Added new article

---

docs-md/basics/decorators.md

This way, syntax highlighting works.

Update code fences to specify typescript

---

docs-md/basics/component-lifecycle.md
docs-md/basics/forms.md
docs-md/basics/handling-arrays.md
docs-md/basics/stencil-config.md
docs-md/basics/testing.md

Fixes the wrong links described in #71.

Fix links of next/back buttons on several doc pages

---

src/components/demos-page/demos-page.tsx

Fixing source for the stencil demo page

fix-stencil-source

---

docs-md/addons/stencil-router.md
docs-md/advanced/css-variables/index.md

docs(several pages): fix navigation button

---

docs-md/addons/stencil-router.md
docs-md/advanced/css-variables/index.md
docs-md/advanced/framework-integration/index.md
docs-md/basics/stencil-config.md

Fixes https://github.com/ionic-team/stencil-site/issues/103 and more.

docs(): fix typos

---

docs-md/advanced/shadow-dom/index.md

Added an article about Shadow Parts

docs(shadow-dom): Shadow Parts Article

---

src/components/stencil-site/stencil-site.tsx

chore() update copyright year

---

.gitignore
docs-md/basics/decorators.md

The arguments to functions using `@Watch` is backwards. It was `oldValue, newValue`; it should be `newValue, oldValue`.
Riding along is a second commit that adds the `tags` file to `.gitignore`, for those of us still using ctags. 
Thanks!

Fix watch docs

---

docs-md/start/index.md

Update to make sentence make more sense.
Fixes: #128

Documentation fix

---

src/components/pwas-page/pwas-page.tsx

Added instruction for production ready PWA out of the box

pwas(): Include step for Building PWAs with Stencil

---

src/docs-content/basics/stencil-config.html
src/docs-md/basics/stencil-config.md

Just a quick correction for a small typo.
Addresses issue #163

docs(config): Minor typo correction

---

src/docs-content/start/index.html

Didn't create an issue first as the contributing suggest because I think it would be a bit overkill for a small typo. Let me know if it is really needed.

Fix typo in package name

---

src/docs-md/guides/server-side-rendering.md

ref https://github.com/ionic-team/stencil/issues/734

update ssr docs

---

src/docs-content/reference/decorators.html
src/docs-content/reference/styling.html
src/docs-md/reference/decorators.md
src/docs-md/reference/styling.md

chore(typos)

---

scripts/host-to-firebase.js

Adding dynamic keys for firebase hosting

Fix host to firebase

---

src/docs-content/framework-integration/react.html
src/docs-content/guides/framework-integration.html
src/docs-md/framework-integration/react.md
src/docs-md/guides/framework-integration.md

noticed an error in the React example

fixed React framework-integration code

---

scripts/markdown-renderer.ts

Solves problems like this:
Not sure if that's the best solution though, would like to get feedback on this one.

sometimes there is nothing to escape which causes unwanted escapes later

---

src/assets/docs-structure.json
src/docs/testing/e2e-testing.md
src/docs/testing/overview.md
src/docs/testing/unit-testing.md

Resync of https://github.com/ionic-team/stencil-site/pull/211.
This also fixes some URL issues I was having generating a few of the testing pages

docs: more unit & e2e testing content

---

src/docs/tooling/config.md

(to be completed with other options)

devServer config

---

src/docs/framework-integration/angular.md
src/docs/framework-integration/react.md
src/docs/framework-integration/vue.md

docs(integrations): change the path to defineCustomElements()

---

src/docs/testing/overview.md
src/docs/testing/unit-testing.md

Just some suggestions for making the docs less wordy and more  to-the-point in one case and filling them out a bit in the unit testing case.

docs(testing): update the testing documentation

---

src/docs/routing/overview.md

Hello,
Add information regarding Apache 2 & Nginx configuration of a Stencil app using stencil-router.
Related to issue #240 
I hope it suits here !
Thanks,

doc(router): add explanations about Apache & Nginx

---

src/docs/components/templating-and-jsx.md

As discussed with @adamdbradley in https://github.com/ionic-team/stencil/issues/1196.
The info is mostly from https://reactjs.org/docs/lists-and-keys.html#keys.

docs(jsx): add info about using keys in loops

---

src/docs/components/templating-and-jsx.md

whoops, did a bad `this` binding 🙄

docs(jsx): fix onClick in "loops and keys" example

---

src/docs/components/methods.md

docs(method): async methods

---

src/docs/framework-integration/vue.md

Removed excess slash

---

src/docs/framework-integration/angular.md

Following our discussion on the Slack channel about how to consume Web Components build with Stencil in an Angular project, we had the idea to add an example about this in the documentation
Feel free to improve it

docs: example using components with ViewChild in Angular

---

package.json
src/docs/README.md
src/docs/components/component.md
src/docs/components/host-element.md
src/docs/components/methods.md
src/docs/components/properties.md
src/docs/components/reactive-data.md
src/docs/components/state.md
src/docs/tooling/docs-auto-generation.md
src/docs/tooling/module-bundling.md
src/docs/tooling/plugins.md

Update highlighting and ensure that the site structure is being built from the README.md file.

Correct the code highlighting and the site-structure README.md file.

---

src/docs/components/api.md

I saw a very small typo and figured I'd submit a PR.  Looking forward to trying Stencil!

docs(): Fix typo in api.md

---

firebase-base.json

chore(): fix /docs redirect

---

src/components/notfound-page/notfound-page.tsx

docs(404): fix typo

---

src/components/resources-page/resources-page.tsx
src/docs/guides/style-guide.md

- Add note to [Stencil Style Guide](https://stenciljs.com/docs/style-guide/) intro (suggest [TSLint](https://palantir.github.io/tslint/), [tslint-ionic-rules](https://github.com/ionic-team/tslint-ionic-rules/blob/master/tslint.js), optionally [tslint-stencil](https://www.npmjs.com/package/tslint-stencil))
- Add [tslint-stencil](https://www.npmjs.com/package/tslint-stencil) to [Resources](https://stenciljs.com/resources)

docs(style-guide): add tslint note

---

src/docs/framework-integration/react.md

:wave: Hi friends.
This PR is a followup to a [conversation in the Stencil slack](https://stencil-worldwide.slack.com/archives/C79EANFL7/p1545159061633100?thread_ts=1545156967.632900&cid=C79EANFL7) and includes the addition of a note to the React integration docs along with a link to https://custom-elements-everywhere.com/.

docs: Add note to React integration docs

---

src/assets/docs-structure.json
src/docs/README.md
src/docs/components/functional-components.md

feat: add section about functional components

---

src/docs/introduction/my-first-component.md

Either mention you need to create it or drop it from the example, otherwise you are greeted with:
```
[ ERROR ]  Unable to load style src/components/my-first-component.css from src/components/my-first-component.tsx
```

docs: my-first-component without CSS

---

src/components/resources-page/resources-page.tsx

Hi there,
I would like to add my side project D3-Stencil in the paragraph Third-party Components.
Thanks in advance!
Edgar.

docs(resources): add d3-stencil to third-party components

---

src/assets/docs-structure.json
src/docs/README.md
src/docs/testing/mocking.md

* add testing/mocking.md
* update components.d.ts
* set stencil version to beta.5

Add testing/mocking.md (#388)

---

src/docs/framework-integration/angular.md

with new stencil one we have to import stenciljs components from test-components/loader, so without the dist folder

docs(): new import folder for stencil components

---

src/docs/guides/redux.md

Stencil redux docs with a demo walkthrough

Adding stencil redux docs

---

src/docs/config/overview.md

document global script

---

src/docs/components/state.md

* Adding basic example usage to State
* Including missing type declaration
* Code formatting example

Add example to state

---

src/components/site-menu/site-menu.tsx

Fixed a minor formatting mistake. Added a space before curly bracket of SiteMenu class.

Added space before curly bracket

---

src/docs/guides/hydrate-app.md

Hydrate Docs Typo

---

src/docs/components/host-element.md

Use the adverb form of 'declarative'

fix(host-element.md): grammar

---

CONTRIBUTING.md

Open to changes. This seems like the more updated way of going about adding a page to the docs.
closes #533

chore(contributing): update contributing guidelines

---

src/docs/guides/workers.md

I saw a spelling error.  I went to update that spelling error and my chrome plugin, Grammarly, pointed out some more potential grammar/spelling corrections.  I've made some of those changes.

Updated workers.md for grammar and spelling

---

src/docs/components/methods.md

This was unclear to me from reading the docs. Finally figured out how to do this from here https://stackoverflow.com/questions/50272576/stenciljs-method-not-working

Clarify that public methods needs to be called asynchronously

---

src/docs/framework-integration/angular.md

update loader path based on v1.8.5 default config

Update Angular integration loader path

---

src/docs/framework-integration/vue.md

Update loader import path based on v1.8.5

Update Vue integration loader import path

---

src/docs/output-targets/docs-json.md

Fix broken link to typescript declarations for the JSON output.

Fix broken link

---

src/docs/config/cli.md

docs(cli): adds documentation on generate cmd

---

src/assets/docs-structure.json
src/docs/README.md
src/docs/introduction/why-stencil.md
src/docs/static-site-generation/basics.md
src/docs/static-site-generation/debugging.md
src/docs/static-site-generation/deployment.md
src/docs/static-site-generation/meta.md
src/docs/static-site-generation/overview.md
src/docs/static-site-generation/server-side-rendering-ssr.md

Adds first pass at Static Site Generation docs (aka pre-rendering)

First SSG Docs

---

src/docs/introduction/faq.md

docs(faq): add more info on browser support

---

src/components/pwas-page/pwas-page.tsx

Add .container to wrapper div to make the page style look consistent

add .container class to wrapper

---

src/components/demo-card/demo-card.css
src/components/resources-page/resources-page.css
src/components/resources-page/resources-page.tsx
src/global/style/variables.css

adds search bar to filter links by title 
change layout to a tabbed layout to better organize content

site(resources page): new layout

---

src/docs/components/component-lifecycle.md

link to each item to the corresponding docs section

docs(lifecycle): make chart interactive

---

src/components/resources-page/resources-data.ts

Points to a Stencil collection with the `My First Component` from the user guide and our basic `Counter` starter kit.
User can edit the components right away and there is minimal branding.

[Resources-page] Adds link to WebComponents.dev

---

src/docs/output-targets/dist.md

Changes in the file: `src/docs/output-targets/dist.md`

docs(output-targets):  change the word 'threeshakable' to 'treeshakable'

---

src/components/resources-page/resources-data.ts

@adamdbradley let me know if I did this correctly!

Add stencil testing cheatsheet to resources page

---

src/docs/framework-integration/bindings.md

Tense fix for write
Clean up on subject of sentence 
Spelling fix for originally

Grammar for bindings.md

---

src/docs/output-targets/custom-elements.md

Removed duplicated "this" from "Legacy Browsers" paragraph

Update custom-elements.md - type fix

---

src/docs/output-targets/custom-elements.md

Small typo correction

---

src/docs/output-targets/custom-elements.md

- General corrections
- Added webpack config
- Added rollup config
- Added assets section

Improve custom elements bundle docs

---

src/docs/testing/screenshot-visual-diff.md

Update screenshot-visual-diff.md typo in example

---

src/docs/components/events.md

Feature implemented in https://github.com/ionic-team/stencil/pull/1162

docs(events): add defaultPrevented to example

---

src/components/resources-page/resources-data.ts

Adding stencil components
1. Swipe detector component.
2. Progress bar spinner inspired from angular material.
3. Step by step guide on how to use stencil components in Angular, React, Vue and Plain Html/JavaScript
4. Product and Cart showcase to use as Micro Front

Adding new stencil components

---

src/docs/guides/publishing.md

Quick note to explain what the collection properties do.
I wonder if we should provide a Stencil app example under "Framework Integration", since consuming Stencil packages in Stencil comes up a lot in Slack. 🤔

Explain what the collections properties do

---

src/components/resources-page/resources-data.ts

1. Added template for using Firebase in Stencil web app along with Stencil Store
2. Fix component resource title

Adding template for Firebase + Stencil

---

src/components/resources-page/resources-data.ts

Added stencil based component with high complexity.
Represents complex virtual grid. Component is growing, will be improved in meantime.

New stencil based component

---

src/docs/framework-integration/react.md

Small typo in the React integration doc.

docs: typo correction

---

src/assets/docs-structure.json
src/docs/README.md
src/docs/testing/screenshot-connector.md

docs: ✏️ add screenshot connector documentation page

---

src/components/resources-page/resources-data.ts

This PR is meant to add a link for a 3rd party Component which I have built using stencil.

Added a resource for 3rd Party Component

---

src/docs/output-targets/custom-elements.md

Remove an extra "includes" from "includes includes"

docs(custom-elements) remove typo

---

src/docs/components/reactive-data.md

Was initially not clear found someone who had the same question on SO https://stackoverflow.com/questions/67717860/stenciljs-can-watch-be-used-on-state

Clarification on using @Watch on @State

---

src/assets/docs-structure.json
src/components/app-root/app-root.tsx
src/components/site-menu/site-menu.tsx
src/docs/README.md
src/docs/telemetry.md
src/global/definitions.ts

Also allows opting out of listing parent sections in the sidebar.
Internal ticket ID: STENCIL-35

docs(telemetry): Add Telemetry page

---

src/docs/telemetry.md

We need to PR to make Vercel deploy automatically.

Update type in telemetry.md

---

src/docs/config/overview.md

Merge when https://github.com/ionic-team/stencil/pull/2989 is merged.

Update config to document invisiblePrehydration

---

src/components/doc-component/doc-component.css

Fix formatting on some heading's that get parsed in order to add a link icon

---

src/docs/framework-integration/angular.md

Nearly final of Angular's updated documentation! All feedback is welcome!

Update Angular Documentation

---

src/docs/framework-integration/react.md

Updating docs for creating React component library

💥 Updating react docs

---

src/docs/framework-integration/angular.md

The output targets all require Stencil v2.9.0 and up

Clarify Stencil Version

---

src/docs/framework-integration/angular.md

1. Rewrite the HTML on the angular page now that HTML type is supported
2. Sync up the support with the React docs

A couple tweaks to Angular

---

src/docs/guides/publishing.md

Hi,
This PR update the entry points of the `package.json` of the "Publishing A Component Library" chapter.
It follows actual setup and also reflects those of the starter kit for which I also submitted a [PR](https://github.com/ionic-team/stencil-component-starter/pull/107)

docs: update publishing entry points

---

src/docs/core/dev-server-api.md

startServer isn't exported any more

Update dev server API

---

src/docs/framework-integration/react.md

I think it's what you wanted to have here no ?

wrong cd folder target after cloning react wrapper project

---

src/docs/framework-integration/react.md

fix alignment issue in the output targets setup example

docs(react): fix small alignment issue

---

src/docs/introduction/getting-started.md

reorder the output of the create-stencil cli to match that found in
https://github.com/ionic-team/create-stencil/pull/56

doc(getting-started): reorder cli output message

---

src/docs/components/events.md

Added information about when `@Listen` event listeners are added and removed.

docs(events): add more info to `@Listen`

---

src/docs/config/cli.md

This is tied to the following PR: https://github.com/ionic-team/stencil/pull/3516

feat: 🎸 add "--no-build"-documentation in CLI-docs

---

src/docs/components/templating-and-jsx.md

Rewrite this section to clarify a little bit what the `key` attr will do and why you'd want to use it. The stuff there already was odd so I rewrote it for the most part.
Part of addressing ionic-team/stencil#3253

docs(jsx): rewrite the section on "loops" to clarify `key` usage

---

src/docs/introduction/upgrading-to-stencil-three.md

See https://github.com/ionic-team/stencil/pull/3777

docs(v3): update the v3 update guide for composition event changes

---

src/docs/introduction/upgrading-to-stencil-three.md

with v3 entering pre-release, this commit updates
the verbiage of the upgrade guide to reflect that

chore(v3): designate v3 as pre-release

---

vercel.json

This reverts commit 9321a291acb5275280caf8b8244c078287b5ae70.

fix(vercel config): redirect urls

---

src/css/custom.scss

Updates the sizing and positioning of the version banner as seen on the "Next" version to match the main container sizing/positioning.

fix(version-banner): banner matches container width/position

---

docusaurus.config.js

update the tagline to better reflect stencil's purpose

doces(meta): update tagline

---

src/util/resources-data.ts

Removes blog posts/resources that were linking to a 404.

fix(resources): remove 404 links from resources

---

docs/introduction/01-overview.md
versioned_docs/version-v3.0/introduction/01-overview.md

Just was reading through and thought a few things could maybe be worded a bit better.

some proposed copy changes on our introduction/overview page

---

ionic-preset-classic/src/styles/custom.scss

This will make striped rows of tables the same background as unstriped rows.

style(theme): No striped tables

---

.gitignore
vercel.json

Reverts ionic-team/stencil-site#1071

Revert "Fix/versioned redirects"

---

CONTRIBUTING.md

this commit updates CONTRIBUTING.md to mention volta setup

chore(repo): add volta to contributing.md

---

docs/introduction/02-goals-and-objectives.md
versioned_docs/version-v3.2/introduction/02-goals-and-objectives.md

Just found this while reading through [Goals and Objectives](https://stenciljs.com/docs/goals-and-objectives).

Add missing period

---

docs/documentation-generation/docs-readme.md
versioned_docs/version-v3.2/documentation-generation/docs-readme.md

Just a little polish / rewording work on the docs-readme OT docs page.

docs(readme): update documentation for docs-readme OT

---

docs/reference/support-policy.md

documentation for https://github.com/ionic-team/stencil/pull/4315

docs(support): add entry for typescript 5 to support policy

---

docs/introduction/upgrading-to-stencil-four.md

this commit includes the final changes to the v4 documentation.
---
it should not be merged until (GA) release day.

docs(v4): finalize v4 documentation

---

docs/reference/support-policy.md

this commit updates the nomenclature/tables for stencil support following v4's release

docs(support): update support policy for v4

---

docs/framework-integration/vue.md
versioned_docs/version-v2/framework-integration/vue.md
versioned_docs/version-v3/framework-integration/vue.md
versioned_docs/version-v4.0/framework-integration/vue.md

Correct the wrong content.
project.json   ->  package.json

docs(vue): Fix vue.md content error

---

docs/reference/support-policy.md

For https://github.com/ionic-team/stencil/pull/4718

docs(support): add ts 5.1.6 / stencil 4.2.0 to version table

---

docs/reference/support-policy.md
versioned_docs/version-v4.0/reference/support-policy.md
versioned_docs/version-v4.1/reference/support-policy.md
versioned_docs/version-v4.2/reference/support-policy.md
versioned_docs/version-v4.3/reference/support-policy.md
versioned_docs/version-v4.4/reference/support-policy.md
versioned_docs/version-v4.5/reference/support-policy.md
versioned_docs/version-v4.6/reference/support-policy.md

Once approved I'll propagate to the other v4 docs I think

chore(support): update support table entry for v2

---

docs/config/cli.md
versioned_docs/version-v4.0/config/cli.md
versioned_docs/version-v4.1/config/cli.md
versioned_docs/version-v4.2/config/cli.md
versioned_docs/version-v4.3/config/cli.md
versioned_docs/version-v4.4/config/cli.md
versioned_docs/version-v4.5/config/cli.md
versioned_docs/version-v4.6/config/cli.md
versioned_docs/version-v4.7/config/cli.md

add the docs task to the cli documentation. also add a small intro for
the cli, to specify what it's for and how it's distributed
I'll propagate this back to all v4 entries once approved

docs(cli): add docs task 

---

docs/introduction/03-getting-started.md
versioned_docs/version-v2/introduction/03-getting-started.md
versioned_docs/version-v3/introduction/03-getting-started.md
versioned_docs/version-v4.0/introduction/03-getting-started.md
versioned_docs/version-v4.1/introduction/03-getting-started.md
versioned_docs/version-v4.2/introduction/03-getting-started.md
versioned_docs/version-v4.3/introduction/03-getting-started.md
versioned_docs/version-v4.4/introduction/03-getting-started.md
versioned_docs/version-v4.5/introduction/03-getting-started.md
versioned_docs/version-v4.6/introduction/03-getting-started.md
versioned_docs/version-v4.7/introduction/03-getting-started.md

Just noticed this code block was missed. I'll port to all the other pages where this is present once approved.

chore(intro): add npm2yarn directive to a code block

---

package-lock.json
package.json

Updates docusuarus preset to latest and Docusaurus dependencies to 3.1.0.
Closes #1311

chore: Docusaurus 3.1, latest preset

---

versioned_docs/version-v4.11/reference/support-policy.md

It turns out I missed to commit this to my branch before I hit the merge button.

docs(support-policy): add end of support note to v4.11 docs

---

docs/config/01-overview.md
versioned_docs/version-v2/config/01-overview.md
versioned_docs/version-v3/config/01-overview.md
versioned_docs/version-v4.0/config/01-overview.md
versioned_docs/version-v4.1/config/01-overview.md
versioned_docs/version-v4.10/config/01-overview.md
versioned_docs/version-v4.11/config/01-overview.md
versioned_docs/version-v4.2/config/01-overview.md
versioned_docs/version-v4.3/config/01-overview.md
versioned_docs/version-v4.4/config/01-overview.md
versioned_docs/version-v4.5/config/01-overview.md
versioned_docs/version-v4.6/config/01-overview.md
versioned_docs/version-v4.7/config/01-overview.md
versioned_docs/version-v4.8/config/01-overview.md
versioned_docs/version-v4.9/config/01-overview.md

Just documenting what this does and sort of suggesting a potential use-case for it.
Once this looks good I'll port to other versions.

chore(docs): add some documentation for the `buildDist` config option

---

docs/config/cli.md
versioned_docs/version-v4.12/config/cli.md

Related to https://github.com/ionic-team/stencil/pull/5425

docs(cli): add documentation of `version` aliases

---

docs/testing/stencil-testrunner/02-config.md

This adds some new interfaces including `screenshotTimeout`.

chore(test): update testing API

---

docs/testing/playwright/02-e2e-testing.md
versioned_docs/version-v4.13.0/testing/playwright/02-e2e-testing.md
versioned_docs/version-v4.14/testing/playwright/02-e2e-testing.md
versioned_docs/version-v4.15/testing/playwright/02-e2e-testing.md
versioned_docs/version-v4.16/testing/playwright/02-e2e-testing.md

Spelling stuff and adding a test example

Playwright docs updates

---

package-lock.json
package.json

This PR:
- bumps Docusaurus deps to `3.4.0` min
- bumps Ionic Docs Preset to `1.2.7` min
Resolves #1390

chore(deps): bump docusaurus for 3.4 compatability

---

docusaurus.config.js
src/css/custom.scss

This PR:
- Adds OS announcement bar to Docusaurus config options
- Adds OS announcement bar styles to local styles

feat(): os announcement bar and styles

---

docs/config/01-overview.md
versioned_docs/version-v3/config/01-overview.md
versioned_docs/version-v4.0/config/01-overview.md
versioned_docs/version-v4.1/config/01-overview.md
versioned_docs/version-v4.10/config/01-overview.md
versioned_docs/version-v4.11/config/01-overview.md
versioned_docs/version-v4.12/config/01-overview.md
versioned_docs/version-v4.13.0/config/01-overview.md
versioned_docs/version-v4.14/config/01-overview.md
versioned_docs/version-v4.15/config/01-overview.md
versioned_docs/version-v4.16/config/01-overview.md
versioned_docs/version-v4.17/config/01-overview.md
versioned_docs/version-v4.18/config/01-overview.md
versioned_docs/version-v4.2/config/01-overview.md
versioned_docs/version-v4.3/config/01-overview.md
versioned_docs/version-v4.4/config/01-overview.md
versioned_docs/version-v4.5/config/01-overview.md
versioned_docs/version-v4.6/config/01-overview.md
versioned_docs/version-v4.7/config/01-overview.md
versioned_docs/version-v4.8/config/01-overview.md
versioned_docs/version-v4.9/config/01-overview.md

fixes [#1611](https://github.com/ionic-team/stencil/issues/1611)

docs(config): document 'env' configuration

---

docs/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v3/testing/e2e-testing.md
versioned_docs/version-v4.0/testing/e2e-testing.md
versioned_docs/version-v4.1/testing/e2e-testing.md
versioned_docs/version-v4.10/testing/e2e-testing.md
versioned_docs/version-v4.11/testing/e2e-testing.md
versioned_docs/version-v4.12/testing/e2e-testing.md
versioned_docs/version-v4.13.0/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v4.14/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v4.15/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v4.16/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v4.17/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v4.18/testing/stencil-testrunner/05-e2e-testing.md
versioned_docs/version-v4.2/testing/e2e-testing.md
versioned_docs/version-v4.3/testing/e2e-testing.md
versioned_docs/version-v4.4/testing/e2e-testing.md
versioned_docs/version-v4.5/testing/e2e-testing.md
versioned_docs/version-v4.6/testing/e2e-testing.md
versioned_docs/version-v4.7/testing/e2e-testing.md
versioned_docs/version-v4.8/testing/e2e-testing.md
versioned_docs/version-v4.9/testing/e2e-testing.md

Requires https://github.com/ionic-team/stencil/pull/5839 to be merged and released first.

docs(testing): document options for newE2EPage

---

renovate.json5

Lowers the frequency of renovate updates to once a month

chore(renovate): lower update frequency

---

cspell-wordlist.txt
docs/framework-integration/react.md
docs/framework-integration/vue.md
docs/guides/server-side-rendering.md

Adding more docs around doing SSR with Stencil.

docs: add better docs for SSR support

---

docs/guides/storybook.md

This patch adds documentation on how to use StencilJS with Storybook.

feat: add storybook guide

---

docs/guides/server-side-rendering.md
versioned_docs/version-v4.23/guides/server-side-rendering.md
versioned_docs/version-v4.24/guides/server-side-rendering.md
versioned_docs/version-v4.25/guides/server-side-rendering.md
versioned_docs/version-v4.26/guides/server-side-rendering.md
versioned_docs/version-v4.27/guides/server-side-rendering.md
versioned_docs/version-v4.28/guides/server-side-rendering.md
versioned_docs/version-v4.29/guides/server-side-rendering.md
versioned_docs/version-v4.30/guides/server-side-rendering.md
versioned_docs/version-v4.31/guides/server-side-rendering.md

Improvements on how we differentiate our SSR approach in Next.js

chore(ssr): improved documentation on runtime vs compile time based SSR

---

docs/components/styling.md
docs/config/01-overview.md

This PR enhances the Stencil documentation to explain how global styles work with shadow DOM components through constructable stylesheets, and provides examples of targeting specific components using the `:host()` pseudo-class.
This hasn't worked before but was implemented in https://github.com/stenciljs/core/pull/6268 and will be released with the next minor release.
The current documentation mentions global styles but doesn't explain how they interact with shadow DOM components. Users may not realize that global styles can directly target and style shadow DOM components, or how to use the `:host()` selector effectively for component-specific styling.
- **Added Constructable Stylesheets section** to `docs/components/styling.md`
- Explains how global styles are automatically registered to …

docs: add constructable stylesheets documentation for global styles

---

docs/guides/storybook.md
versioned_docs/version-v4.33/guides/storybook.md

Closes #1529 
@christian-bromann

docs: amend storybook.md with instructions for Storybook v9

---

docs/framework-integration/vue.md

Adds documentation changes for this PR: https://github.com/stenciljs/output-targets/pull/689

docs: add `eventAttr` description in vue integration docs
